### ISSUE TITLE
tag 前面加空格后 后端就报错

### ISSUE THREAD

**Issue by xwinie** [airbnb/enzyme#1009]
op：
```jsx
render() {

		return (
			<div className="app">
				<h1>Reaclux Boilerplate</h1>
				<p>A React Redux Webpack Gulp Sass Mocha Enzyme Zombie Chai Boilerplate by   <span>Punkbit</span></p>
			</div>
		);

	}
```
<span> before, leave a blank space
error msg：
```sh
[13:52:59] Error in plugin 'gulp-mocha'
Message:
    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
Stack:
Error: react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
    at Object.<anonymous> (/Volumes/data/work/source/reaclux-boilerplate/node_modules/enzyme/build/react-compat.js:108:11)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/data/work/source/reaclux-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/data/work/source/reaclux-boilerplate/node_modules/enzyme/build/Utils.js:65:20)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/data/work/source/reaclux-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

dependencies：

"babel-core": "^6.13.2",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "chai": "^3.5.0",
    "cheerio": "^0.22.0",
    "css-loader": "^0.23.1",
    "enzyme": "^2.9.1",
    "file-loader": "^0.9.0",
    "gulp": "^3.9.1",
    "gulp-mocha": "^3.0.1",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.7",
    "html-webpack-plugin": "^2.22.0",
    "jsdom": "^9.5.0",
    "lodash": "^4.15.0",
    "mocha": "^3.0.2",
    "mocha-jsdom": "^1.1.0",
    "node-sass": "^3.8.0",
    "open": "0.0.5",
    "popmotion": "^5.0.18",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-hot-loader": "^1.3.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.7.0",
    "react-router-redux": "^4.0.5",
    "react-test-renderer": "^15.6.1",
    "redux": "^3.5.2",
    "redux-mock-store": "^1.2.0",
    "redux-thunk": "^2.1.0",
    "sass-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "testdom": "^2.0.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.15.0",
    "zombie": "^4.2.1"
```

**Comment by ljharb** [comment]
Please read the readme; specifically https://github.com/airbnb/enzyme#installation - that will help you install the proper dependencies.

**Comment by ljharb** [comment]
This is no longer relevant with v3.
