### ISSUE TITLE
TypeError: Cannot read property 'getPublicInstance' of undefined with react 16

### ISSUE THREAD

**Issue by capaj** [airbnb/enzyme#1106]
I am trying out jest with react 16 and I get:
```
    TypeError: Cannot read property 'getPublicInstance' of undefined
      
      at WrapperComponent.getWrappedComponent (node_modules/enzyme/build/ReactWrapperComponent.js:95:31)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:100:34)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/components/common/PickUsersModal.spec.js:8:30)

```

when I try to `mount` my react component. shallow and render work fine

**Comment by ljharb** [comment]
enzyme is not yet compatible with react 16; as `npm ls` will show you.

You'll have to downgrade react or wait for enzyme v3.
