### ISSUE TITLE
Cannot read property 'type' of null on ''.type()

### ISSUE THREAD

**Issue by teod** [airbnb/enzyme#113]
If returning an empty string/null inside a react component and trying to call the type() function on that node will result in the following  error: Cannot read property 'type' of null. This can be reproduced when trying to the use the shallow rendering filterWhere() API method. 
Please see the below code snippet:

```javascript
const MyComp = ({foo}) => {
    return (
          <div>
                 <MyOtherComp />
                 {foo !== 0 && (
                      <MyAnotherComp />
                  )}
          </div>
    );
});

it('should rock the world', () => {
    const wrapper = shallow(<MyComp foo={0});
    const result = wrapper.findWhere(n => (
          n.type() ===  MyAnotherComp
    );
   expect('nothing because "Cannot read property \'type\' of null" will occur');
});
```
In my test I want to check if the value of a specific prop is for e.g. {bar} then component should not be rendered.
Are there any workarounds for this issue ?
Thanks !

**Comment by ljharb** [comment]
Could you make your `findWhere` function be `n => n && n.type() === MyAnotherComp`?

**Comment by teod** [comment]
ljharb, I actually tried to do exactly that the outcome is still the same ...

**Comment by ljharb** [comment]
Is there a stack trace?

**Comment by teod** [comment]
I'm not sure if it will help but here is the console output, I'm using webpack:
```
     [exec]     TypeError: Cannot read property 'type' of null
     [exec]         at ShallowWrapper.<anonymous> (/home/[PRIVACY]/tests.webpack.js:115316:18)
     [exec]         at ShallowWrapper.single (/home/[PRIVACY]/tests.webpack.js:115578:18)
     [exec]         at ShallowWrapper.type (/home/[PRIVACY]/tests.webpack.js:115315:20)
     [exec]         at /home/[PRIVACY]/tests.webpack.js:216028:34
     [exec]         at /home/[PRIVACY]/tests.webpack.js:115503:17
     [exec]         at /home/[PRIVACY]/tests.webpack.js:115751:10
     [exec]         at treeForEach (/home/[PRIVACY]/tests.webpack.js:115742:4)
     [exec]         at /home/teodordruta/[PRIVACY]/tests.webpack.js:115744:13
     [exec]         at Array.forEach (native)
     [exec]         at treeForEach (/home/[PRIVACY]/tests.webpack.js:115743:25)

```

In tests.webpack.js at line 115316:
```javascript
	    key: 'type',
	    value: function type() {
	      return this.single(function (n) {
	        return n.type;
	      });
	    }
```

In tests.webpack.js at line 115578:
```javascript
	    key: 'single',
	    value: function single(fn) {
	      if (this.length !== 1) {
	        throw new Error('This method is only meant to be run on single node. ' + this.length + ' found instead.');
	      }
	      return fn.call(this, this.node);
	    }
```

Line 216028 is my test.
And Line 115503 is:
```javascript
	    key: 'findWhere',
	    value: function findWhere(predicate) {
	      var _this15 = this;
	
	      return findWhereUnwrapped(this, function (n) {
	        return predicate(_this15.wrap(n));
	      });
	    }
```

**Comment by ljharb** [comment]
Thanks - looks like perhaps https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L419-L427 is assuming that `n` won't ever be `null`.

**Comment by smacker** [comment]
it happens because wrapper.node.props.children = [<MyOtherComp>, false];

So `n => (n.node && n.type() === MyAnotherComp)` will work.

**Comment by teod** [comment]
@smacker, that seems to do its job as a workaround for now, Thanks !

**Comment by smacker** [comment]
@ljharb the problem is not only there. Another example:

```javascript
    describe('should works with null, undefined and false types', () => {
      const IfComponent = (node) => {
        return (node && <div />);
      };

      it('failed', () => {
        const wrapper = new ShallowWrapper(IfComponent(null));
      });
    });
```

it throws error in createRendererCompatible, because you use node.type there too: `if (typeof node.type === 'string') {`.

Maybe it's better to filter falsy children somewhere?

**Comment by mistadikay** [comment]
Any progress on this guys? I have the same problem, but with `n.props()`. See the stack trace below:

```
TypeError: Cannot read property 'props' of null
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:466:51)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:958:19)
      at ReactWrapper.props (node_modules/enzyme/build/ReactWrapper.js:465:21)
      at ReactWrapper.js:15:41
      at node_modules/enzyme/build/ReactWrapper.js:853:18
      at findAllInRenderedTreeInternal (node_modules/enzyme/build/MountedTraversal.js:260:13)
      at findAllInRenderedTreeInternal (node_modules/enzyme/build/MountedTraversal.js:272:24)
      at findAllInRenderedTreeInternal (node_modules/enzyme/build/MountedTraversal.js:275:22)
      at treeFilter (node_modules/enzyme/build/MountedTraversal.js:285:10)
      at _class.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:39:45)
      at node_modules/enzyme/build/ReactWrapper.js:828:21
      at Array.map (native)
      at _class.flatMap (node_modules/enzyme/build/ReactWrapper.js:827:32)
      at findWhereUnwrapped (node_modules/enzyme/build/ReactWrapper.js:38:18)
      at _class.findWhere (node_modules/enzyme/build/ReactWrapper.js:852:16)
```

Happens only on stateless (pure-function) components.

**Comment by smacker** [comment]
@lelandrichardson 

Test case from https://github.com/airbnb/enzyme/issues/113#issuecomment-170860946 still fail.

```
  1) shallow should works with null, undefined and false types failed:
     TypeError: Cannot read property 'type' of null
      at Object.render (react-compat.js:88:20)
      at new ShallowWrapper (ShallowWrapper.js:62:21)
      at Context.<anonymous> (ShallowWrapper-spec.js:1649:23)
```

**Comment by ljharb** [comment]
@smacker thanks, I'll take a look at that today.
