### ISSUE TITLE
Enzyme 3.0.0 - Class added to element in componentDidMount isn't found with wrapper.find()

### ISSUE THREAD

**Issue by savinger** [airbnb/enzyme#1212]
Repo: https://github.com/savinger/enzyme-issue

```
import 'babel-polyfill';
import React from 'react';
import Enzyme, { mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

class MyComponent extends React.Component {
  
  componentDidMount() {
    this.ref.classList.add('test');
  }
  
  render() {
    return (
      <div>
        <div ref={ el => { this.ref = el; }}></div>
      </div>
    );
  }
}

test('issue', () => {
    
  let wrapper = mount(<MyComponent />);

  // element with "test" class is visible in markup
  console.log(wrapper.html()); 

  // returns 0
  expect(wrapper.find('.test').length).toBe(1);

  // still returns 0
  // wrapper.update();
  // expect(wrapper.find('.test').length).toBe(1);
});
```

```
$ npm test

> enzyme-issue@1.0.0 test /Users/spenceravinger/GitHub/enzyme-issue
> jest

 FAIL  ./test.js
  ✕ issue (29ms)

  ● issue

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      1
    Received:
      0
      
      at Object.<anonymous> (test.js:36:40)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  console.log test.js:28
    <div><div class="test"></div></div>

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.594s, estimated 2s
Ran all test suites.
```

**Comment by abotchen** [comment]
I have the same problem

**Comment by ljharb** [comment]
@savinger That's mutation - that's not how classes are meant to be added. You should setState, and add the class name on rerender.
