### ISSUE TITLE
Cannot read property 'bind' of undefined in domutils

### ISSUE THREAD

**Issue by ucabaur** [airbnb/enzyme#1225]
Hi,
Running into this issue when using enzyme on my project (i'm only shallow rendering a div element for the test)

Here is the stack trace
```
TypeError: Cannot read property 'bind' of undefined
      
      at node_modules/domutils/index.js:12:27
      at Array.forEach (native)
      at node_modules/domutils/index.js:11:19
      at Array.forEach (native)
      at Object.<anonymous> (node_modules/domutils/index.js:10:3)
      at Object.<anonymous> (node_modules/css-select/lib/pseudos.js:14:19)
      at Object.<anonymous> (node_modules/css-select/index.js:5:21)
      at Object.<anonymous> (node_modules/cheerio/lib/static.js:6:14)
      at Object.<anonymous> (node_modules/cheerio/lib/api/attributes.js:1:98)
      at Object.<anonymous> (node_modules/cheerio/lib/cheerio.js:19:3)
      at Object.<anonymous> (node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:11:16)
      at Object.<anonymous> (node_modules/enzyme/build/index.js:6:21)
      at Object.<anonymous> (tests/components/FooBar.test.js:6:41)
```
And the last element of the stack trace
```
var DomUtils = module.exports;
[
  require("./lib/stringify"),
  require("./lib/traversal"),
  require("./lib/manipulation"),
  require("./lib/querying"),
  require("./lib/legacy"),
  require("./lib/helpers")
].forEach(function(ext){
  Object.keys(ext).forEach(function(key){
    DomUtils[key] = ext[key].bind(DomUtils);
  });
});
```

**Comment by ljharb** [comment]
What does `npm ls` output? If it exits nonzero, nothing can be expected to work
