### ISSUE TITLE
parent() not work

### ISSUE THREAD

**Issue by HsuTing** [airbnb/enzyme#1230]
After I upgrade to `react@16` and `enzyme@3`. `parent()` does not work for me.
 
I try to use `wrapper.parent()`, and it returns `null` to me.
However, `wrapper.parents().first()` does work. It returns the correct component.

**Comment by eddiemonge** [comment]
maybe wrapper isn't the actual wrapper. I think parent() is broken as well. See https://github.com/airbnb/enzyme/issues/1373

**Comment by chriswatrous** [comment]
I'm also having a problem with `.parent()`. I get an error when I try to simulate an event on the return from `.parent()` but not with `.parents().at(0)`.

Test script:
```
import React from 'react';
import {mount} from 'enzyme';

const runTest = (findParent) => {
  let value = false;
  const wrapper = mount(
    <div>
      <div id='parent' onClick={() => value = true}>
        <div id='child'/>
      </div>
    </div>
  );
  const parent = findParent(wrapper);
  console.log('parent =', parent.debug());
  parent.simulate('click');
  expect(value).toBe(true);
}

describe.only('', () => {
  // passes
  it('', () => runTest((wrapper) => wrapper.find('#parent')));

  // passes
  it('', () => runTest((wrapper) => wrapper.find('#child').parents().at(0)));

  // fails
  it('', () => runTest((wrapper) => wrapper.find('#child').parent()));
});
```

Output:
```
 FAIL  test/integration/routes/event-test.spec.js
    ✓  (43ms)
    ✓  (5ms)
    ✕  (11ms)

  ●  ›

    TypeError: Cannot read property 'tagName' of null

      13 |   const parent = findParent(wrapper);
      14 |   console.log('parent =', parent.debug());
    > 15 |   parent.simulate('click');
      16 |   expect(value).toBe(true);
      17 | }
      18 |

      at node_modules/react-dom/lib/ReactTestUtils.js:323:34
      at Object.simulateEvent (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:199:15)
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)
      at runTest (test/integration/routes/event-test.spec.js:15:10)
      at Object.<anonymous> (test/integration/routes/event-test.spec.js:27:16)

  console.log test/integration/routes/event-test.spec.js:14
    parent = <div id="parent" onClick={[Function: onClick]}>
      <div id="child" />
    </div>

  console.log test/integration/routes/event-test.spec.js:14
    parent = <div id="parent" onClick={[Function: onClick]}>
      <div id="child" />
    </div>

  console.log test/integration/routes/event-test.spec.js:14
    parent = <div id="parent" onClick={[Function: onClick]} />

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        2.342s, estimated 3s
```

react@15.6.2
enzyme@3.3.0

**Comment by ljharb** [comment]
@chriswatrous I believe your issue is covered by #1373.

I'm going to close this; please file new issues for other concerns.

**Comment by huchenme** [comment]
@ljharb this still happens for 3.5.0 `wrapper.parent()` not working but `wrapper.parents().first()` does

**Comment by ljharb** [comment]
@huchenme can you file a new issue, with repro steps?

**Comment by upupming** [comment]
@ljharb Hi, I am encountering this bug, too. This is a repo for reproducing the bug: https://github.com/upupming/enzyme-parent-bug

**Comment by ljharb** [comment]
@upupming thanks for filing a new issue, #1991.

**Comment by KorayAydemir** [comment]
parent() still does not work but parents().at(0) works and returns correct element
