### ISSUE TITLE
Strange cheerio->lodash error when running enzyme with jest

### ISSUE THREAD

**Issue by Tetheta** [airbnb/enzyme#1246]
Here's the error I'm getting:

```console
Test suite failed to run

    TypeError: memoizeCapped is not a function

      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_stringToPath.js:17:20)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_castPath.js:3:20)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseGet.js:1:105)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/get.js:1:104)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseMatchesProperty.js:2:11)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseIteratee.js:2:27)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/some.js:2:20)
      at Object.<anonymous> (node_modules/cheerio/lib/api/attributes.js:13:13)
      at Object.<anonymous> (node_modules/cheerio/lib/cheerio.js:21:3)
      at Object.<anonymous> (node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (node_modules/enzyme/build/render.js:10:16)
      at Object.<anonymous> (node_modules/enzyme/build/index.js:21:15)
      at Object.<anonymous> (node_modules/enzyme-matchers/lib/assertions/toContainReact.js:7:15)
      at Object.<anonymous> (node_modules/enzyme-matchers/lib/index.js:23:23)
      at Object.<anonymous> (node_modules/jest-enzyme/lib/index.js:5:23)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
```
Yet the _memoizeCapped function the _stringToPath is trying to include is indeed there. I use get all the time with the latest lodash so I don't think it's lodash causing the issue here. Any ideas? I've tried every configuration/etc thing I can think of that would be an issue.

Also posted over on [cheerio](https://github.com/cheeriojs/cheerio/issues/1094)

Jest config in package.json:
```javascript
	"jest": {
		"unmockedModulePathPatterns": [
			"react",
			"enzyme",
			"jest-enzyme"
		],
		"moduleNameMapper": {
			"\\.(jpe?g|png|gif|eot|otf|webp|svg|ttf|woff2?|mp[34]|webm|wav|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
			"\\.(css|less|s[ac]ss|styl)$": "<rootDir>/__mocks__/styleMock.js",
			"app": "<rootDir>/src/app.js"
		},
		"moduleFileExtensions": [
			"js",
			"jsx"
		],
		"moduleDirectories": [
			"src",
			"src/js",
			"node_modules"
		],
		"setupTestFrameworkScriptFile": "./node_modules/jest-enzyme/lib/index.js"
	},
```

.babelrc:
```javascript
{
	"presets": [
		[
			"env",
			{
				"modules": false,
				"targets": { "browsers": "ie >= 11, ff >= 46, > 1%" },
				"useBuiltIns": true,
				"debug": false
			}
		],
		"react"
	],
	"plugins": [
		"transform-class-properties",
		"transform-object-rest-spread"
		//'react-hot-loader/babel',
	],
	"env": {
		"test": {
			"presets": [
				"env",
				// {
				// 	"modules": false,
				// 	"targets": { "browsers": "ie >= 11, ff >= 46, > 1%" },
				// 	"useBuiltIns": true,
				// 	"debug": false
				// }
				"react"
			],
			"plugins": [
				"transform-class-properties",
                "transform-object-rest-spread",
                "transform-export-extensions"
			],
			"only": ["./**/*.js", "node_modules/jest-runtime"]
		}
	}
}
```

**Comment by ljharb** [comment]
This definitely doesn't seem like an enzyme issue at all; I'm going to close it, but we can certainly keep discussing it.

**Comment by Tetheta** [comment]
Yeah doesn't seem like it is, but it only happened after updating enzyme (I don't have cheerio/etc as dependencies ) so was hoping it had happened to someone else in the upgrade to React 16/etc.

**Comment by shashank-ac** [comment]
> Yeah doesn't seem like it is, but it only happened after updating enzyme (I don't have cheerio/etc as dependencies ) so was hoping it had happened to someone else in the upgrade to React 16/etc.

Please update us with any progress you made, did you find out what went wrong ?
