### ISSUE TITLE
Enzyme 3.* fails with "@Import ..." from scss files.

### ISSUE THREAD

**Issue by samuxyz** [airbnb/enzyme#1313]
Hey guys,

Yesterday I updated Enzyme from 2 to the latest version in order to use React 16 and the majority of my tests passed (which is great!).

However I still have 6-7 failures in a specific situation:
As I use css modules by importing .scss files, whenever the .scss file contains `@import '/path/another/scss/file'` a test fails with the following error:

```
/my-project/dashboard/src/components/VerifyInstallation/result-block.scss: Unexpected token (1:0)
      > 1 | @import '~stylesheets/mixins';
          | ^
        2 | @import '~stylesheets/variables';
        3 |
        4 | .result-container {
```

In my package.json file I defined `moduleNameMapper`:

```json
"moduleNameMapper": {
      "^.+\\.(scss|css|svg|png|sass)$": "identity-obj-proxy"
    }
```

And in Enzyme 2 I did not encounter this error.

An example of failing test is the following:

```js
import React from 'react';
import { shallow } from 'enzyme';
import { shallowToJson } from 'enzyme-to-json';
import { ResultBlock } from 'components/VerifyInstallation/ResultBlock';
import styles from 'components/VerifyInstallation/result-block.scss';

const intl = {
  formatMessage: () => 'code snippet failed message',
};

describe('<ResultBlock />', () => {
  let wrapper;
  beforeEach(() => {
    wrapper = shallow(
      <ResultBlock intl={intl} />
    );
  });

  it('should render initial components', () => {
    expect(shallowToJson(wrapper)).toMatchSnapshot();
  });
});
```

Notice that I imported `styles` in the spec file otherwise I receive the following error (I did not import it initially with Enzyme 2):

```
<ResultBlock /> › should render initial components

    TypeError: val.forEach is not a function

      at Object.<anonymous> (tests/components/VerifyInstallation/ResultBlock.spec.js:20:55)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```
And I am out of clues on how to solve it.

Any suggestions?
Thank you!

**Comment by ljharb** [comment]
It's definitely not related to enzyme.

I'm not sure what's using `p-map` (if it's your component, could you provide the code for that too?)

Can you do the `shallowToJson` and `toMatchSnapshot` calls on separate lines? It's possible one or both of those doesn't yet work with enzyme 3.

**Comment by samuxyz** [comment]
@ljharb so today I updated some packages again.

Now the current result for the test is the following:

```
<ResultBlock /> › should render initial components

    TypeError: val.entries is not a function

      at Object.<anonymous> (tests/components/VerifyInstallation/ResultBlock.spec.js:21:5)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```
`p-map` apparently disappeared.

I separated `shallowToJson` and `toMatchSnapshot` in 2 lines so line **21** is related to `toMatchSnapshot`.

I Checked the result from `shallowToJson` and I get this:

```
{ type: 'div',
        props: { className: 'result-container' },
        children:
         [ { type: 'img',
             props: [Object],
             children: null,
             '$$typeof': Symbol(react.test.json) },
           { type: 'div',
             props: [Object],
             children: [Object],
             '$$typeof': Symbol(react.test.json) } ],
        '$$typeof': Symbol(react.test.json) }
```

the code for the component is the following: 

```
import PropTypes from 'prop-types';
import React, { PureComponent } from 'react';
import styles from './result-block.scss';
import greenIcon from 'images/success-check.svg';
import redIcon from 'images/red-warning.svg';
import { FormattedMessage, FormattedDate } from 'react-intl';
import verifyInstallation from './locale';

export default class ResultBlock extends PureComponent {

  static propTypes = {
    detections: PropTypes.object,
    isIframe: PropTypes.bool,
  }

  static defaultProps = {
    detections: { success: false, checked_at: '' },
    isIframe: false,
  }

  render () {
    const {
      detections: { success, checked_at },
      isIframe,
    } = this.props;

    return (
      <div className={styles['result-container']}>
        <img src={success ? greenIcon : redIcon} alt="images" />
        <div className={styles['result-msg']}>
          <h4 className={styles.title}>
            {
              success
              ? <FormattedMessage {...verifyInstallation.success} />
              : <FormattedMessage {...verifyInstallation.fail} />
            }
          </h4>
          <p>
            {
              success
              ? <FormattedMessage {...verifyInstallation.successMsg} />
              : <FormattedMessage
                  {...verifyInstallation.failMsg}
                  values={{
                    snippet: isIframe ? <strong>&lt;iframe&gt;</strong> : <strong>&lt;script&gt;</strong>,
                    snippetEnd: isIframe ? <strong>&lt;/iframe&gt;</strong> : <strong>&lt;/script&gt;</strong>,
                    tag: isIframe ? <strong>&lt;body&gt;</strong> : <strong>&lt;head&gt;</strong>,
                  }}
                />
            }
          </p>
          <p>
            <FormattedMessage {...verifyInstallation.lastChecked} />:&nbsp;
            <FormattedDate
              value={new Date(checked_at * 1000)}
              year="numeric"
              month="long"
              day="2-digit"
              timeZone="America/New_York"
            />
          </p>
        </div>
      </div>
    );
  }
}
```
**PS**: The component is now exported as default so I also import it without `{` in the test file as I removed a useless wrapper.

current setup:
Enzyme `3.1.0` and Jest `21.2.1`.

**Comment by samuxyz** [comment]
@ljharb Ok so I sort of found out the reason:
The tests fails whenever the component imports svg files and use them directly in the render:
```
import greenIcon from 'images/success-check.svg';
import redIcon from 'images/red-warning.svg';

...

<img src={success ? greenIcon : redIcon} alt="images" />
```

However when I use the svg files as background in the css the tests pass.

**Comment by samuxyz** [comment]
@ljharb ok I did actually made it. It's not Enzyme issue, perhaps Jest. Once i mocked the svg/assets files by following their guide https://facebook.github.io/jest/docs/en/webpack.html it solved.

With Jest 20 I encountered no problems though.

Anyway thanks I am going to close the issue.
