### ISSUE TITLE
shallow renderer is not available in production mode

### ISSUE THREAD

**Issue by jorgeortega** [airbnb/enzyme#1326]
I have this error in the gitlab test pipeline, all tests pass locally, any ideas?

```
FAIL src/components/ui/Button/__tests__/Button.spec.jsx
  ● Test suite failed to run

    shallow renderer is not available in production mode.
        at Error (native)
      
      at Object.<anonymous> (node_modules/react-test-renderer/shallow.js:4:9)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:21:16)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/index.js:2:18)
      at Object.<anonymous> (src/components/ui/Button/__tests__/Button.spec.jsx:3:27)
```

**Comment by ljharb** [comment]
Did you figure out that this is related to `NODE_ENV` being set to ‘production’?

**Comment by jorgeortega** [comment]
I did, but I’m not sure what sets it to production by default, could it be the default value in gitlab?

**Comment by ljharb** [comment]
That's possible; I don't use gitlab so I'm not sure.
