### ISSUE TITLE
Parent is not a consistent with other searches

### ISSUE THREAD

**Issue by eddiemonge** [airbnb/enzyme#1373]
Enzyme 3

The last test here throws an error 

```
    describe.only('enzyme test', () => {
      const onClick = jest.fn();
      const wrapper = mount(
        <div className="div-elem">
          <span className="parent-elem" onClick={onClick}>
            <span className="child-elem">click me</span>
          </span>
        </div>
      );

      it('child should fire onClick', () => {
        wrapper.find('.child-elem').simulate('click');
        expect(onClick).toHaveBeenCalledTimes(1);
      });

      it('parents should fire onClick', () => {
        wrapper.find('.child-elem').parents('.parent-elem').simulate('click');
        expect(onClick).toHaveBeenCalledTimes(2);
      });

      it('closest should fire onClick', () => {
        wrapper.find('.child-elem').closest('.parent-elem').simulate('click');
        expect(onClick).toHaveBeenCalledTimes(3);
      });

      it('parent should fire onClick', () => {
        wrapper.find('.child-elem').parent().simulate('click');
        expect(onClick).toHaveBeenCalledTimes(4);
      });
    })
```

```
TypeError: Cannot read property 'tagName' of null

      at node_modules/react-dom/lib/ReactTestUtils.js:325:35
      at Object.simulateEvent (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:199:15)
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)
```

**Comment by ljharb** [comment]
@eddiemonge does this also occur with shallow?

**Comment by eddiemonge** [comment]
not sure. shouldnt be hard to figure out though. should also probably be a test for both for this case

**Comment by ljharb** [comment]
@eddiemonge would you be willing to submit a PR that has failing test cases? (or even better, a fix?)

**Comment by ljharb** [comment]
I've added your tests from the OP to master: https://github.com/airbnb/enzyme/commit/1b4a9e0da22941506ba0ae41e7d2ba34396641ba

Since they pass, I'm going to close this - happy to reopen it if there's further issues.
