### ISSUE TITLE
Shallow rendering keeps throwing error.

### ISSUE THREAD

**Issue by codepressd** [airbnb/enzyme#1402]
Been fighting with this for a whole day and hoping it is something simple. 

Been trying to shallow render my React Components, but I keep having it error out. It seems to run through every file/component that is imported in and the import files of those files until finally it finds somewhere to break. The error has nothing to do with the component I'm trying to test or should even affect it...

It also seems to require having jsdom(or some type of mock dom), which I didn't think was required when doing a shallow render.

I don't know if anyone has seen this issue or any pointers on how to fix it?

We are using Typescript, React 16, Enzyme Adapter 16, mocha, chai, jsdom.

Thanks in advance.

**Comment by ljharb** [comment]
If you simply enter the node repl, and try to require your component, does it work?

**Comment by codepressd** [comment]
@ljharb I don't know if I'm doing it right but I get a cannot find module.

I cd into my components folder and started the REPL and tried to require my component.
```
require("./mycomponent");
```
I did the same for enzyme and it found the module no problem.

Thanks

**Comment by ljharb** [comment]
You can only require `.js` files in the repl, not `.ts` or `.jsx` files - are you requiring build output, or, using something like `babel-register` or similar so that you can transpile files on the fly?

**Comment by codepressd** [comment]
@ljharb 
We're using ts-node/register.  I'm also requiring mock-local-storage, ignore-styles and have jsDom being setup with in a testSetup.js.  The majority of that was added to troubleshoot this problem...

Thanks for your help!

**Comment by ljharb** [comment]
If this has been addressed, can it be closed?

**Comment by codepressd** [comment]
@ljharb 
I'm still having the issue...

Depending on the component we try to render we get a different error. It's like it is not really shallow rendering, or could be I don't fully understand what happens when a component is shallow rendered. 

But right now if we import from like a utils file or whatever... everything in that file and what ever is connected to that file is being "examined" by the shallow render. 

So pretty much we're stuck just testing super simple components at this point...

I don't know if that helps.

**Comment by ljharb** [comment]
@codepressd the implication is that if you have a test file *that doesn't even import enzyme*, just imports the component, that you'd get the same errors.

Can you provide an example stack trace with something that breaks?

**Comment by codepressd** [comment]
@ljharb 
```
/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/Index.tsx:5 
import * as numeral from "numeral";
                                                                             ^
TypeError: ApiClient.getBundleJsHash is not a function
    at versionCheck (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/Index.tsx:5:78)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/Index.tsx:9:48)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/ApiClient.ts:1:43055)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/components/StatsPage.tsx:1:28391)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/components/AnalyticsChart.tsx:1:15826)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/src/components/AnalyticsDrilldownPage.tsx:1:15036)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/test/AnalyticsDrilldown.spec.tsx:12:1)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:392:23)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:395:12)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:612:30)
    at Module.replacementCompile (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/ts-node/src/index.ts:384:14)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at runMain (/Users/chrisreeder/.node-spawn-wrap-7961-0fb623054597/node:68:10)
    at Function.<anonymous> (/Users/chrisreeder/.node-spawn-wrap-7961-0fb623054597/node:171:5)
    at Object.<anonymous> (/Users/chrisreeder/projects/new-dashboard/src/DashboardV3/ui/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at /Users/chrisreeder/.node-spawn-wrap-7961-0fb623054597/node:178:8
    at Object.<anonymous> (/Users/chrisreeder/.node-spawn-wrap-7961-0fb623054597/node:181:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3```

This error will change depending on different components.
Thanks

**Comment by ljharb** [comment]
@codepressd ok, so that file - could you share the first 5 lines in it?

**Comment by codepressd** [comment]
@ljharb 
Test File:
```
// import * as mocha from "mocha";
// import * as React from "react";
// import * as chai from "chai";
// import * as enzyme from "enzyme";
// import * as sinon from "sinon";
```
I don't know if you wanted the the component file , the one it broke? Its just going to be imports on all of them. 

Also we use typescript so the next thing after the imports are going to be our interface for the component.

**Comment by ljharb** [comment]
@codepressd so, none of those should have `import * as` - `import React from 'react'`, for example, is correct (typescript's new behavior that forces this is simply incorrect).

(I was asking about line 5 in `ui/src/Index.tsx`, not in the test file)

**Comment by codepressd** [comment]
```function versionCheck() {
    ApiClient.getBundleJsHash(hash => {
        // We're being extra careful here. If any data is missing (some unknown
        // problem occurred) then we don't reload. Otherwise we could get in an
        // endless loop.
        if (hash.statusCode === 200 && hash.data && window["__bundleJsHash"] && hash.data !== window["__bundleJsHash"]) {
            window.location.reload();
        }
    }, error => {
        // Do nothing, just continue.
    });
}

versionCheck();
```

Here is those lines of code where it breaks in index.tsx, but like I said it will do this in random spots around the app, just depends on which component I try to use.
j

**Comment by ljharb** [comment]
OK, so it seems like you're relying on a shared stateful object `ApiClient` - are you sure `getBundleJsHash` is being defined in the same file that `ApiClient` is created in?

**Comment by codepressd** [comment]
@ljharb 

So we import all of ApiClient  like ```import * as ApiClient from "../ApiClient.ts";```

inside api client file is a the function 
```
export const getBundleJsHash = (
    done: (apiResult: ApiResult<string>) => void,
    failure: FailureCallback,
) => {
    callAPI("GET", undefined, "bundleJsHash", done, failure);
};
```

callApi handles all of the actual requests 

So I don't know if that helps

**Comment by ljharb** [comment]
@codepressd the error `TypeError: ApiClient.getBundleJsHash is not a function` suggests that it's some combination of the way typescript is exporting and being imported; indeed from your `export const getBundleJsHash`, it should be a function - unless you have a circular dependency? If so, you should rearchitect to remove it; they're a code smell and can cause issues where exported values aren't initially available.
