### ISSUE TITLE
Issue With Test Cases which are using render after updating enzyme & react to latest versions

### ISSUE THREAD

**Issue by ghost** [airbnb/enzyme#1403]
Can some one please help me below is the issue which i'm getting when i'm running the test cases.

After updating test cases which are using shallow are working fine but the test cases which are using render are failing .

```jsx
import React from 'react'
import { expect } from 'chai'
import { shallow, render } from 'enzyme'

import { EndOfWorkIconCell, EventTypeCell } from './FileName'

const endWorkUnitEvent = {
    payload: {
        properties: {
            endWorkUnit: true,
            schemaName: 'TrainActivated'
        }
    }
}

const nonEndWorkUnitEvent = {
    payload: {
        properties: {
            endWorkUnit: false,
            schemaName: 'TrainActivated'
        }
    }
}

describe('the EndOfWorkIconCell component', () => {
    it('renders a <Button> tag if it is an endWorkUnit event', () => {
        const wrapper = render(<EndOfWorkIconCell rowData={endWorkUnitEvent} icon="info-circle" />)
        expect(wrapper.find('button')).to.have.length(1)
    })

    it('renders nothing if it is not an endWorkUnit event', () => {
        const wrapper = render(<EndOfWorkIconCell rowData={{}} icon="info-circle" />)
        expect(wrapper.find('button')).to.have.length(0)
    })
})

describe('the EventTypeCell component', () => {
    it('renders a <span> tag with the formatted schemaName for endWorkUnit=true event', () => {
        const wrapper = shallow(<EventTypeCell rowData={endWorkUnitEvent} />)
        expect(wrapper.find('span')).to.have.length(1)
        expect(wrapper.find('span').text()).to.be.equal('Train Activated Details')
    })

    it('renders a <span> tag with the formatted schemaName for endWorkUnit=false event', () => {
        const wrapper = shallow(<EventTypeCell rowData={nonEndWorkUnitEvent} />)
        expect(wrapper.find('span')).to.have.length(1)
        expect(wrapper.find('span').text()).to.be.equal('Train Activated')
    })
})

```

```sh
> 

  384 passing (2s)
  2 pending
  18 failing

  1) the component renders a .label element:
     AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0
      at Context.<anonymous> (C:/Users/Desktop/Project-Name/src/main/javascript/components/controls/FileName.test.js:10:48
)
      at callFn (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:320:5)

  2) the EndOfWorkIconCell component renders a <Button> tag if it is an endWorkUnit event:
     AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0
      at Context.<anonymous> (C:/Users/Desktop/Project-Name/src/main/javascript/components/controls/FileName.test.js:28:48)
      at callFn (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:320:5)
```
Below list of dependencies and devDependencies
```json
"dependencies": {
    "bootstrap": "^3.3.7",
    "css-loader": "^0.23.1",
    "enzyme-adapter-react-16": "^1.1.0",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "^0.9.0",
    "fixed-data-table": "^0.6.3",
    "flux": "^2.1.1",
    "font-awesome": "^4.7.0",
    "gel-bootstrap-3": "^0.6.23",
    "google-maps-react": "^1.0.19",
    "invariant": "^2.2.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "loader-utils": "^1.1.0",
    "lodash": "^4.16.6",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.6",
    "promise": "^7.1.1",
    "prop-types": "^15.5.8",
    "react": "^16.0.0",
    "react-bootstrap": "^0.31.0",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.0.0",
    "react-esri-map": "^0.1.20",
    "react-flexbox": "^3.1.1",
    "react-hotkeys": "^0.10.0",
    "react-infinite-scroller": "^1.1.1",
    "react-overlays": "^0.6.10",
    "react-router": "^2.5.2",
    "react-router-bootstrap": "^0.23.2",
    "react-router-transition": "0.0.5",
    "react-scroll": "^1.5.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "whatwg-fetch": "^0.11.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.11.0",
    "babel-register": "^6.14.0",
    "better-npm-run": "0.0.8",
    "chai": "^3.5.0",
    "chai-enzyme": "^1.0.0-beta.0",
    "cheerio": "^1.0.0-rc.2",
    "copy-webpack-plugin": "^2.1.1",
    "enzyme": "^3.1.1",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^5.2.2",
    "eventsource-polyfill": "^0.9.6",
    "globule": "^1.0.0",
    "h2o2": "^5.4.0",
    "hapi": "^13.3.0",
    "hapi-webpack-plugin": "^1.3.0",
    "html-webpack-plugin": "^2.29.0",
    "inert": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "json-loader": "^0.5.4",
    "mocha": "^2.5.3",
    "mocha-junit-reporter": "^1.11.1",
    "nodemon": "^1.11.0",
    "nyc": "^7.1.0",
    "react-addons-perf": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-hot-api": "^0.4.5",
    "react-hot-loader": "^1.3.0",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-hot-middleware": "^2.6.0"
  }
}
```

**Comment by Santhuraoi** [comment]
@ljharb Please help me on this asap

**Comment by ljharb** [comment]
Where is the test called "the component renders a .label element:"?

**Comment by Santhuraoi** [comment]
@ljharb can you check the second failure test case please

**Comment by ljharb** [comment]
@Santhuraoi i see the failure message. i'm asking for the test code; the test code you pasted doesn't have that description.

**Comment by Andsbf** [comment]
This could be related to: https://github.com/airbnb/enzyme/issues/1420

**Comment by ljharb** [comment]
Since the OP deleted their account, I'm going to close this since we won't be able to get a repro case.
