### ISSUE TITLE
Attempted to wrap undefined property componentDidMount as function

### ISSUE THREAD

**Issue by steftastan** [airbnb/enzyme#1414]
Hello, I am following the documentation and a previously asked question just like this to the letter but I just can't get this test to work. I'd like to test the lifecycle for an Accordion component on my page.

The Accordion class is defined in a file of mine called App.js, I'm only including part of its code, it's logic and render methods are way too long anyway.

**App.js (in ../src/App)**
```
class Accordion extends Component {

    constructor() {
      super();
      this.filterLinkList = this.filterLinkList.bind(this);
      this.toggleElem = this.toggleElem.bind(this);
      this.state = {
          data: {},
          companies: {}
      };
    }

    componentDidMount() {
        $.ajax({
            url: '/data.json',
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });

        $.ajax({
            url: '/companies.json',
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({companies: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    }

    componentDidUpdate() {
        document.addEventListener('keyup', this.filterLinkList, false);
    }
 }
```

**And my test, Accordion.spec.js**
```
import React from 'react';
import Accordion from '../src/App';
import { configure, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

describe('<Accordion />', () => {
    it('calls componentDidMount', () => {
        const wrapper = mount(<Accordion />);
        spy(Accordion.prototype, 'componentDidMount');
        expect(Accordion.prototype.componentDidMount.calledOnce).to.equal(true);
    });
});
```

It's also worth mentioning I've declared all my imports in a separate file, which is why you don't see them in Accordion.spec.js. They are in a file called helpers.js

**helpers.js**
```
import { expect } from 'chai';
import { sinon, spy } from 'sinon';
import { mount, render, shallow } from 'enzyme';

global.expect = expect;
global.sinon = sinon;
global.spy = spy;

global.mount = mount;
global.render = render;
global.shallow = shallow;

```

I have no idea what I'm doing wrong, I am following the documentation to the letter.

Also worth mentioning I followed this tutorial here: http://blog.ricardofilipe.com/post/react-enzyme-tdd-tutorial

Please help :C

**Comment by brenthosie** [comment]
Sorry, I don't have a specific answer to your issue on testing mount. But when I was reading over your code I noticed that you're attaching an event listener every time your component updates.

```
componentDidUpdate() {
    document.addEventListener('keyup', this.filterLinkList, false);
}
```

You should move that portion of your code into `componentDidMount` or `componentWillMount` and also clean up your event listener on `componentWillUnmount`

**Comment by steftastan** [comment]
Thanks for the tip! I moved that line of coude to my componentDidMount() function and removed the event listenener on WillUnmount.

**Comment by ljharb** [comment]
@steftastan you have to spy on the function *before* creating the wrapper in the first place.

**Comment by steftastan** [comment]
Thanks for the help @ljharb, unfortunately I tried that, still didn't work. I also tried putting it outside the it(); function, still nothing.

I guess it'd be worth sharing more information on my issue. Weirdly everytime a test fails I get a npm error log. I'll try to include everything that happens on the console whenever I try to run a test.

```
  1) <Accordion />
       calls componentDidMount:
     TypeError: Attempted to wrap undefined property componentDidMount as function
      at wrapMethod (node_modules\sinon\lib\sinon\util\core\wrap-method.js:70:21)
      at Object.spy (node_modules\sinon\lib\sinon\spy.js:35:16)
      at Context.<anonymous> (C:/Users/etastan/test-commonsensev2.0/test/Accordion.spec.js:17:11)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! commonsensev2.0@0.1.0 test: `mocha --compilers js:babel-register --require ./test/helpers.js --require ./test/dom.js --recursive`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the commonsensev2.0@0.1.0 test script 'mocha --compilers js:babel-register --require ./test/helpers.js --require ./test/dom.js --recursive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the commonsensev2.0 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --compilers js:babel-register --require ./test/helpers.js --require ./test/dom.js --recursive
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs commonsensev2.0
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls commonsensev2.0
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\etastan\test-commonsensev2.0\npm-debug.log
```

Thanks :S

**Comment by brenthosie** [comment]
@steftastan is your component wrapped in anything like `Redux`'s `connect` function? Or are you exporting `Accordion` as the default?

**Comment by steftastan** [comment]
I am exporting Accordion as a default, actually, I am exporting like this:




I have my main component App where I call all the components that make up my page like so:

```
class App extends Component {

    render() {
        return (
          <div className="wrapper wrapper__app App">
            <Header />
            <Accordion />
            <BreadCrumbs/>
            <Dashboard />
          </div>
        );
    }
}

```
and then I export that component:

`
export default App;
`

Not using Redux but I don't have a limitation on what I can or can't use, not sure if it's worth it?

**Comment by ljharb** [comment]
@steftastan sinon can't spy on functions that don't exist; if there's no `componentDidMount`, why are you trying to spy on it?
