### ISSUE TITLE
AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0

### ISSUE THREAD

**Issue by bing4all** [airbnb/enzyme#1421]
After updating enzyme to version 3 all the test cases which are importing render from enzyme are failing Mainly the .find(selector)from cheerio is throwing error with length zero(0) but the actual length is 1 ,

Please see the debug below where i tried to debug the complete wrapper with the find label 

Below is test case error 
```
396 passing (2s)
  2 pending
  18 failing

  1) the xxxx component renders a .label element:
     AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0
      at Context.<anonymous> (C:/Users/Desktop/Project/tj-view/src/main/javascript/components/controls/FileName.test.js:11:48)
```

Below  is my test file 
```jsx
import React from 'react'
import { expect } from 'chai'
import { render } from 'enzyme'

import xxxx, { deviationMinutesStyle, deviationMinutesText } from './xxxx'

describe('the xxxx component', () => {
    it('renders a .label element', () => {
        const wrapper = render(<xxxx/>)
        console.log(wrapper.find('.label'))
        expect(wrapper.find('.label')).to.have.length(1)
    })
})

describe('the deviationMinutesStyle helper function', () => {
    it('should be success(green) when deviationMinutes is positive the train is ahead of schedule', () => {
        expect(deviationMinutesStyle(0)).to.be.equal('success')
        expect(deviationMinutesStyle(1)).to.be.equal('success')
    })

    it('should be warning(yellow) when deviationMinutes is negative [-1, -60] the train is marginally behind of schedule', () => {
        expect(deviationMinutesStyle(-1)).to.be.equal('warning')
        expect(deviationMinutesStyle(-60)).to.be.equal('warning')
    })

    it('should be danger(red) when deviationMinutes is negative (< -60) the train is way behind of schedule', () => {
        expect(deviationMinutesStyle(-61)).to.be.equal('danger')
    })
})

describe('the deviationMinutesText helper function', () => {
    it('should be "N minutes late" where N < -1', () => {
        expect(deviationMinutesText(-2)).to.be.equal('2 minutes late')
    })

    it('should be "N minute late" where N = -1', () => {
        expect(deviationMinutesText(-1)).to.be.equal('1 minute late')
    })

    it('should be "no deviation" where N = 0', () => {
        expect(deviationMinutesText(0)).to.be.equal('no deviation')
    })

    it('should be "N minute early" where N = 1', () => {
        expect(deviationMinutesText(1)).to.be.equal('1 minute early')
    })

    it('should be "N minutes late" where N < -1', () => {
        expect(deviationMinutesText(-2)).to.be.equal('2 minutes late')
    })
})
```

debug 
```
 the xxxx component
initialize {
  options:
   { withDomLvl1: true,
     normalizeWhitespace: false,
     xml: false,
     decodeEntities: true },
  _root:
   initialize {
     '0':
      { type: 'tag',
        name: 'span',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': [Object],
        'x-attribsPrefix': [Object],
        children: [],
        parent: null,
        prev: null,
        next: null,
        root: [Object] },
     options:
      { withDomLvl1: true,
        normalizeWhitespace: false,
        xml: false,
        decodeEntities: true },
     length: 1,
     _root: [Circular] },
  length: 0,
  prevObject:
   initialize {
     '0':
      { type: 'tag',
        name: 'span',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: [Object],
        'x-attribsNamespace': [Object],
        'x-attribsPrefix': [Object],
        children: [],
        parent: null,
        prev: null,
        next: null,
        root: [Object] },
     options:
      { withDomLvl1: true,
        normalizeWhitespace: false,
        xml: false,
        decodeEntities: true },
     length: 1,
     _root: [Circular] } }
    1) renders a .label element

```

Below is my package.json file 
```json
> "dependencies": {
    "bootstrap": "^3.3.7",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "^0.9.0",
    "fixed-data-table": "^0.6.3",
    "flux": "^2.1.1",
    "font-awesome": "^4.7.0",
    "gel-bootstrap-3": "^1.0.0",
    "google-maps-react": "^1.0.19",
    "invariant": "^2.2.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "loader-utils": "^1.1.0",
    "lodash": "^4.16.6",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.6",
    "promise": "^7.1.1",
    "prop-types": "^15.5.8",
    "react": "^16.0.0",
    "react-bootstrap": "0.31.5",
    "react-document-title": "2.0.3",
    "react-dom": "^16.0.0",
    "react-esri-map": "^0.1.21",
    "react-flexbox": "^3.1.1",
    "react-hotkeys": "0.10.0",
    "react-infinite-scroller": "1.1.1",
    "react-overlays": "^0.6.10",
    "react-router": "3.0.5",
    "react-router-bootstrap": "0.23.2",
    "react-router-transition": "0.0.5",
    "react-scroll": "^1.5.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "whatwg-fetch": "^0.11.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.11.0",
    "babel-register": "^6.14.0",
    "better-npm-run": "0.0.8",
    "chai": "^3.5.0",
    "chai-enzyme": "1.0.0-beta.0",
    "cheerio": "1.0.0-rc.1",
    "copy-webpack-plugin": "^2.1.1",
    "enzyme": "3.1.1",
    "enzyme-adapter-react-16": "1.0.4",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^5.2.2",
    "eventsource-polyfill": "^0.9.6",
    "globule": "^1.0.0",
    "h2o2": "^5.4.0",
    "hapi": "^13.3.0",
    "hapi-webpack-plugin": "^1.3.0",
    "html-webpack-plugin": "^2.29.0",
    "inert": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "json-loader": "^0.5.4",
    "mocha": "3.5.0",
    "mocha-junit-reporter": "^1.11.1",
    "nodemon": "^1.11.0",
    "nyc": "^7.1.0",
    "react-addons-perf": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-hot-api": "^0.4.5",
    "react-hot-loader": "^1.3.0",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-hot-middleware": "^2.6.0"
  }
}
```

**Comment by ljharb** [comment]
@bing4all can you get your tests passing with enzyme 3 and react 15, before upgrading to react 16? That helps us determine if the issue is in the react 16 adapter, or enzyme 3 overall.

Separately, this might be due to the breaking changes in cheerio.

**Comment by bing4all** [comment]
@ljharb I did the same I have updated only enzyme version and mocha chai version still all the test cases which use render are failing. Please give any solution to this its been a long time i have working on the same issue .

**Comment by bing4all** [comment]
Used console.log to know whats happening, The Below is the image where the test cases were the success.
![capture1s](https://user-images.githubusercontent.com/34318913/33784760-9b3e5b92-dc27-11e7-9005-9b8efcee5aad.PNG)
Used console.log to know whats happening, The Below is the image where the test cases were the failure.
![capture1f](https://user-images.githubusercontent.com/34318913/33784816-dc578694-dc27-11e7-8f97-17aa107a5771.PNG)

**Comment by ljharb** [comment]
@bing4all cheerio 1.0 (used in enzyme 3) has a breaking change; which is that instead of `render` providing a wrapper that *contains* the rendered contents, it now provides a wrapper that *is* the rendered contents.

In other words, you're doing `console.log(wrapper.find('.label'))` - but based on my assumption that `xxxx` literally renders jsx where the root node has a `.label` class, what happens with `console.log(wrapper.is('.label'))`?

**Comment by bing4all** [comment]
@ljharb when i do console.log(wrapper.is('.label') its returning true 

  the DeviationMinutesControl component
true
******************
    1) renders a .label element

  the deviationMinutesStyle helper function
    √ should be success(green) when deviationMinutes is positive the train is ahead of schedule
    √ should be warning(yellow) when deviationMinutes is negative [-1, -60] the train is marginally behind of schedule
    √ should be danger(red) when deviationMinutes is negative (< -60) the train is way behind of schedule


![capture](https://user-images.githubusercontent.com/34318913/33837711-e0f39d0a-de52-11e7-9ac9-c5791eebfb92.PNG)

**Comment by bing4all** [comment]
@ljharb  I stared using JSDOM and editing all the files which use render and change them to mount and all the test cases are doing good but 2 of them are failing.
Please have a look 
![capture](https://user-images.githubusercontent.com/34318913/33838647-b9a54b92-de55-11e7-96b4-5631943e5ab0.PNG)

2) the xxxx component should have a single child <a> tag:
     TypeError: wrapper.find(...).attr is not a function
      at Context.<anonymous> (C:/Users/Desktop/Project/tj-view/src/main/javascript/components/toolbar/xxxx.test.js:16:34)

**Comment by ljharb** [comment]
@bing4all `.attr` is a cheerio method, it's only available with `render`. You may want `.prop`?
