### ISSUE TITLE
Mounting component: TypeError: _configuration2.default.get is not a function

### ISSUE THREAD

**Issue by amelzer** [airbnb/enzyme#1446]
After upgrading a project to React 16 and therefore Enzyme 3 I find myself with failing tests

`npm ls` runs without error
Enzyme version: `3.2.0`
NPM version: `5.6.0`

I am using Jest for the tests.

`mount` is imported like this: `import { mount } from 'enzyme';`

```
   35 |         const expectedSettings = { ... mockSettings, textColor: '#f00' };
      36 |         const onChange = jest.fn();
    > 37 |         const wrapper = mount(<ThemeSettings settings={mockSettings} onChange={onChange} />);
      38 |         wrapper.find('.mock-color-pick').at(0).simulate('click');
      39 |         expect(onChange).toHaveBeenCalledWith(expectedSettings);
      40 |     });
      
      at makeOptions (node_modules/enzyme/build/Utils.js:76:66)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:92:42)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/components/themeSettings/themeSettings.test.js:37:41)
```

**Comment by amelzer** [comment]
So, I found the solution which has nothing to do with Enzyme.

Our jest config had a badly written moduleNameMapper that redirected everything that was called config m)

**Comment by ljharb** [comment]
Glad you figured it out!
