### ISSUE TITLE
Catch error thrown in a ref handler

### ISSUE THREAD

**Issue by d4rkr00t** [airbnb/enzyme#1466]
### Current behavior
There is no way of catching error inside a ref handler:

```js
// Component
class Popup extends React.PureComponent {
  handleRef = () => {
    throw new Error('Try catching me!!!');
  }

  render() {
    return <div ref={this.handleRef}>content</div>;
  }
}

// Test
it('should fail', () => {
  expect(() => mount(<Popup />)).to.throw(Error);
});
```

Result:

```sh
START:
  Popup
    UI
      ✖ should fail
ERROR: 'The above error occurred in the <div> component:
    in div (created by Popup)
    in Popup (created by WrapperComponent)
    in WrapperComponent

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.'
      ✔ should fail if target and popup are not in the same offset parent

Finished in 0.061 secs / NaN secs @ 11:43:09 GMT+1100 (AEDT)

SUMMARY:
✔ 1 test completed
✖ 1 test failed

FAILED TESTS:
  Popup
    UI
      ✖ should fail 
        HeadlessChrome 0.0.0 (Mac OS X 10.13.2)
      Error: Uncaught Error: Try catching me!!!. (build/karma-config/entry.js:69127)
          at Object.invokeGuardedCallbackDev (build/karma-config/entry.js:138832:16)
          at invokeGuardedCallback (build/karma-config/entry.js:138689:27)
          at commitRoot (build/karma-config/entry.js:148301:9)
          at performWorkOnRoot (build/karma-config/entry.js:149268:42)
          at performWork (build/karma-config/entry.js:149218:7)
          at requestWork (build/karma-config/entry.js:149129:7)
          at scheduleWorkImpl (build/karma-config/entry.js:148983:11)
          at scheduleWork (build/karma-config/entry.js:148940:12)
          at scheduleTopLevelUpdate (build/karma-config/entry.js:149444:5)
```

### Expected behavior
Being able to handle the error.

### Your environment
Karma

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React              |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
What happens in React 15? I think this is just how React 16 works with errors, and you'd need a `componentDidCatch` to intercept them.

**Comment by ljharb** [comment]
Closing, since this is just how React 16 works.
