### ISSUE TITLE
Compability with Babel 7

### ISSUE THREAD

**Issue by cking** [airbnb/enzyme#1502]
### Current behavior
Testing with babel 7 throws an error

```
 FAIL  app/components/Tooltip/Tooltip.test.jsx
  ● Test suite failed to run

    TypeError: path.inShadow is not a function

      at ReplaceSupers.ReturnStatement (node_modules/babel-helper-replace-supers/lib/index.js:55:15)
      at NodePath._call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:64:19)
      at NodePath.call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:38:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:99:12)
      at TraversalContext.visitQueue (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:139:18)
      at TraversalContext.visitMultiple (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:93:17)
      at TraversalContext.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:178:19)
      at Function.traverse.node (node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:106:18)
      at TraversalContext.visitQueue (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:139:18)
```

### Expected behavior
The test should succeed, or at least not fail because of a babel version mismatch (use peerDependencies for example)

### Your environment
The full package.json is available at https://gist.github.com/cking/45b2120acdf5da6de5d74eb68c561c61

Windows Bash for Linux using Ubuntu 14.04 LTS
Ubuntu 16.04 LTS

babel ^7.0.0-beta.39
jest ^22.0.4
jest-enzyme ^4.1.1
enzyme ^3.3.0

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | ^3.3.0
| React            |  ^16.0.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'm not sure why this is filed here; babel and enzyme are entirely unrelated, and you don't have to use babel *at all* for it to work - separately, your use of any version of babel shouldn't impact enzyme at all (assuming you are properly *not* transpiling node_modules, which is the default behavior).

It seems like it might be an issue with babel 7, which is still in beta, and your code?

**Comment by cking** [comment]
Alright, it worked with the basic tests, though you might be right. I'm sorry and try researching the issue again.
