### ISSUE TITLE
Cannot read from of undefined

### ISSUE THREAD

**Issue by theskillwithin** [airbnb/enzyme#1531]
```
 FAIL  app/components/Page/test.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'from' of undefined

      1 | import React from 'react'
    > 2 | import { Snackbar } from 'react-toolbox'
      3 |
      4 | import theme from './styles.module.scss'
      5 |

      at Object.<anonymous> (../node_modules/react-toolbox/node_modules/core-js/fn/array/from.js:3:54)
      at Object.<anonymous> (../node_modules/react-toolbox/lib/utils/polyfills.js:3:1)
      at Object.<anonymous> (../node_modules/react-toolbox/lib/index.js:92:1)
      at Object.<anonymous> (components/Toaster/view.js:2:47)
      at Object.<anonymous> (components/Toaster/index.js:10:39)
      at Object.<anonymous> (components/Page/view.js:10:42)
      at Object.<anonymous> (components/Page/index.js:6:39)
      at Object.<anonymous> (components/Page/test.spec.js:4:13)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.23s
Ran all test suites.
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
 sum.js   |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

setup: https://gist.github.com/theskillwithin/388e4bf9e219b2c00586f2c54b4648a7#file-test-spec-js-L1

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a support question, please check our community support resources:
https://facebook.github.io/react/community/support.html
