### ISSUE TITLE
Cannot find module '../maps/decode.json' from 'decode_codepoint.js'

### ISSUE THREAD

**Issue by jefelewis** [airbnb/enzyme#1554]
<h1>Error</h1>
Test suite failed to run

Cannot find module '../maps/decode.json' from 'decode_codepoint.js'
     at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
     at Object.<anonymous> (node_modules/entities/lib/decode_codepoint.js:1:106)

<h1>Package.json</h1>

```json
{
  "name": "topshelf",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack -w",
    "start": "nodemon server/app.js",
    "test": "jest --coverage --silent --forceExit"
  },
  "jest": {
    "presets": "react"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/storage": "^1.6.0",
    "ajax": "0.0.4",
    "axios": "^0.18.0",
    "babel": "^6.23.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^22.4.1",
    "babel-loader": "^7.1.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "body-parser": "^1.18.2",
    "bootstrap": "^4.0.0",
    "busboy": "^0.2.14",
    "child-process-promise": "^2.2.1",
    "cors": "^2.8.4",
    "expect": "^22.4.0",
    "express": "^4.16.2",
    "firebase": "^4.10.1",
    "jquery": "^3.3.1",
    "mongoose": "^5.0.6",
    "nodemon": "^1.15.1",
    "os": "^0.1.1",
    "passport": "^0.4.0",
    "path": "^0.12.7",
    "pg": "^7.4.1",
    "popper.js": "^1.12.9",
    "react": "^16.2.0",
    "react-bootstrap": "^0.32.1",
    "react-bootstrap-navdropdown-active": "^0.2.0",
    "react-dom": "^16.2.0",
    "react-dropzone": "^4.2.8",
    "react-router-dom": "^4.2.2",
    "sequelize": "^4.35.0",
    "webpack": "^3.11.0"
  },
  "devDependencies": {
    "enzyme": "^3.3.0",
    "jest": "^22.4.2",
    "jest-cli": "^22.4.2",
    "json-loader": "^0.5.7"
  }
}
```

<h1>Webpack</h1>

```js
const path = require('path');

module.exports = {
  entry: path.resolve('./client/public/index.js'),
  output: {
    path: path.resolve('./client/public/'),
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.js[x]?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: ['react', 'env', "es2015"]
        }
      },
      {
        test: /\.json$/,
        include: [
          /node_modules/,
          path.resolve(__dirname, '..')
        ],
        loader: 'json-loader'
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx']
  }
}
```

<h1>.Babelrc</h1>

```json
{
  "presets": ["env", "react"]
}
```

**Comment by ljharb** [comment]
I have no idea; but this is entirely unrelated to enzyme. Perhaps jest, since the error is in jest-resolve?

Separately, you might need to add ".json" to the extensions list under "resolve" in your webpack config?
