### ISSUE TITLE
Click event is not getting data attributes

### ISSUE THREAD

**Issue by iiison** [airbnb/enzyme#1572]
### Current behavior
I've added a click event on `tr` in a table, here is code:
```js
rows.map((row, index) => {
  const formattedDataset = {}

  for (const data in rowData.dataset) { // rowData.dataset is an object like this : { id : 'id' }
    formattedDataset[data] = row[rowData.dataset[data]]
  }

  return (
    <tr 
      key={row.id}
      onClick={(event) => {
        event.stopPropagation()

        rowData.onRowClick(event.currentTarget.dataset)
      }}
      {...formattedDataset}
    >
      {showIndex ? <td>{index + 1}</td> : ''}
      {
        headers.map((header) => (<td key={header.id} className={header.classes}>{row[header.id]}</td>))
      }
    </tr>
  )
})
```
Here is how I am simulating click event:
```js
it('simulates row click', () => {
    const tree = invoicesScreen({
      lastSixMonthsInvoices : [
        ...rows data
      ]
    })
    const instance = tree.instance()
    const handleRowClickSpy = jest.spyOn(instance, 'handleRowClick')
    const row = tree
      .find('tr')
      .at(1)

    instance.forceUpdate()

    row.simulate('click', {
      stopPropagation() {},
      currentTarget : {
        dataset : {
          id : 11295
        }
      }
    })

    expect(handleRowClickSpy).toHaveBeenCalled()
  })
```
this click event throws error:
```sh
TypeError: Cannot read property 'id' of undefined

      at Object.InvoicesContainer._this.handleRowClick (app/containers/Finance/InvoicesContainer.jsx:147:4360)
      at onClick (app/components/Table/Table.jsx:56:2415)
      at Object.invokeGuardedCallback [as invokeGuardedCallbackWithCatch] (node_modules/react-dom/lib/ReactErrorUtils.js:24:5)
      at executeDispatch (node_modules/react-dom/lib/EventPluginUtils.js:81:21)
      at Object.executeDispatchesInOrder (node_modules/react-dom/lib/EventPluginUtils.js:106:5)
      at executeDispatchesAndRelease (node_modules/react-dom/lib/EventPluginHub.js:41:22)
      at executeDispatchesAndReleaseSimulated (node_modules/react-dom/lib/EventPluginHub.js:49:10)
      at forEachAccumulated (node_modules/react-dom/lib/forEachAccumulated.js:24:8)
      at Object.processEventQueue (node_modules/react-dom/lib/EventPluginHub.js:250:7)
      at node_modules/react-dom/lib/ReactTestUtils.js:349:22
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:95:27)
      at node_modules/react-dom/lib/ReactTestUtils.js:347:18
      at Object.simulateEvent (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:199:15)
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)
      at Object.<anonymous> (app/containers/Finance/InvoicesContainer.test.js:247:9)
      at process._tickCallback (internal/process/next_tick.js:109:7)

```
### Expected behavior
test should get data attribute 'id' from the `tr` and run without error

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.1.0
| React            |  15.6.1

#### Adapter

- [ ] enzyme-adapter-react-16
- [X] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'd suggest avoiding `simulate` entirely, since it doesn't faithfully simulate anything. Instead, explicitly invoke the prop function you want.
