### ISSUE TITLE
Error With ES6 import statement

### ISSUE THREAD

**Issue by HeratPatel1** [airbnb/enzyme#1586]
[Mount]
```jsx
import { push } from 'react-router-redux';
```
```sh
TypeError: Cannot read property 'length' of undefined
      at TopFilter.switchAgg (src/components/TopFilter.js:4:1)
      at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:491:10)
      at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:438:27)
      at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:452:43)
      at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:836:19)
      at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:858:5)
      at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:956:5)
      at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:964:10)
      at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:937:8)
      at Object.processEventQueue (node_modules/react-dom/cjs/react-dom.development.js:1110:5)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:980:22
      at batchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11082:14)
      at Object.batchedUpdates [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:2330:12)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:974:14
      at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)
      at Context.<anonymous> (test/components/TopFilter.test.js:239:39)
```

**Comment by ljharb** [comment]
Seems like a bug in TopFilter.js - can you share that code?

**Comment by HeratPatel1** [comment]
Component
https://drive.google.com/file/d/1V5GdwqeiYARsPWUSqxCeaAj-cL8pCDvm/view
test file
https://drive.google.com/file/d/1kcF5yOn89WyKH4GFMpveBgaZyR8gxzqI/view

**Comment by ljharb** [comment]
Line 4 doesn’t seem to match the stack trace. I’m unclear on how this is related to enzyme; can you elaborate?
