### ISSUE TITLE
findWhere errors for simple mounted component.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [airbnb/enzyme#1651]
Probably related to #166, this snippet of code errors out on Enzyme 3.3.0:

```js
  const MyComp = () => (<span>hello</span>);

  it("shouldn't throw at least", () => {
    const wrapper = mount(<MyComp/>);
    const result = wrapper.find('span').findWhere(n => n.text() === 'hello');
  });
```

Here's the error: 

```
TypeError: Cannot read property 'textContent' of null
    at ReactWrapper.<anonymous> (...snip.../node_modules/enzyme/build/ReactWrapper.js:799:43)
    at ReactWrapper.single (...snip.../node_modules/enzyme/build/ReactWrapper.js:1534:25)
    at ReactWrapper.text (...snip.../node_modules/enzyme/build/ReactWrapper.js:798:21)
    at ...snip.../spec.jsx:50:61
```

Am I using this wrong?

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.12.6

**Comment by AndrewSouthpaw** [comment]
Sorry, duplicate of #1566. Should've searched first. 😦
