### ISSUE TITLE
Shallow renderer "ReactWrapper::setState() expects a function as its second argument" when setState given a callback within the class

### ISSUE THREAD

**Issue by rydash** [airbnb/enzyme#1769]
**Describe the bug**
Shallow rendering components fails when `setState(updater, callback)` is called within `componentDidUpdate` and `callback` refers to a function within the current component class, accessed via `this`.

**To Reproduce**
1. Create a component like this:
```js
import React from 'react';

class MyComponent extends React.Component {
  constructor() {
    super();
    this.state = {
      isLifecycle: false
    };
  }

  componentDidMount() {
    this.setState({ isLifecycle: true }, this.myCallback('Hello!'));
  }

  myCallback(message) {
    console.log(message);
  }

  render() {
    return <div></div>;
  }
}

export default MyComponent;
```

2. Set up a test:
```js
import React from 'react';
import { shallow } from 'enzyme';
import MyComponent from 'components/MyComponent';

describe('MyComponent', function() {
  it('renders', function() {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.be.ok;
  });
});
```

3. Run the test. (I did so using enzyme@3.4.4, enzyme-adapter-react-16@1.2.0, chai@4.1.2, and mocha@5.2.0. If other packages are relevant, I'm happy to describe them!)

4. Receive the following error:
```
0 passing (22ms)
1 failing

  1) MyComponent
       renders:
     TypeError: ReactWrapper::setState() expects a function as its second argument
      at ShallowWrapper.setState (node_modules/enzyme/build/ShallowWrapper.js:508:17)
      at MyComponent.ShallowWrapper.instance.setState (node_modules/enzyme/build/ShallowWrapper.js:190:35)
      at MyComponent.componentDidMount (src/js/components/MyComponent.js:12:10)
      at /Users/ryanmcgill/repos/fake/node_modules/enzyme/build/ShallowWrapper.js:196:22
      at Object.batchedUpdates (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:392:22)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:195:26)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Context.<anonymous> (test/components/MyComponent.spec.js:7:21)
```

**Expected behavior**
The callback is called with the provided message, and the test succeeds.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: N/A, using node@10.8.0 + mocha@5.2.0 + jsdom@11.11.0

**Additional context**
This was behaving as expected in enzyme@3.4.1.

I am not currently sure which area of the code is causing Enzyme to transform this parameter or otherwise not identify it as a function.

Interestingly, each of the following callback styles will work with enzyme@3.4.4:
```js
  componentDidMount() {
    this.setState({ isLifecycle: true }, () => console.log('Whazzup'));
  }
```
or
```js
  componentDidMount() {
    this.setState({ isLifecycle: true }, () => this.myCallback('Howdy!'));
  }
```

Of course, converting such callbacks to use fat arrow functions may not be feasible or introduce bugs for full applications.

**Comment by rydash** [comment]
Whoops, looks like I should've applied my brain a little harder! Sorry for that - it is interesting that this case went uncaught by eznyme@3.4.1 or even React. It also appears everything works if the return value of `this.myCallback()` is itself a function, so that's good.

Thank you for the explanation; I'll go fix my stuff!
