### ISSUE TITLE
Simulate click on div or span element failed

### ISSUE THREAD

**Issue by xuan45** [airbnb/enzyme#1822]
**Describe the bug**
I want to simulate click on a div or span element, but failed (it can work on a, button elements) and got a error as follows

```js
    TypeError: ReactWrapper::simulate() event 'click' does not exist

      152 |       .first()
      153 |       .childAt(0)
    > 154 |       .simulate('click', {
          |        ^
      155 |         target: {
      156 |           textContent: 2,
      157 |         },

      at Object.simulateEvent (node_modules/_enzyme-adapter-react-16@1.5.0@enzyme-adapter-react-16/build/ReactSixteenAdapter.js:357:23)
      at ReactWrapper.<anonymous> (node_modules/_enzyme@3.6.0@enzyme/build/ReactWrapper.js:917:29)
      at ReactWrapper.single (node_modules/_enzyme@3.6.0@enzyme/build/ReactWrapper.js:1640:25)
      at ReactWrapper.simulate (node_modules/_enzyme@3.6.0@enzyme/build/ReactWrapper.js:916:21)
      at Object.<anonymous> (src/component/KeyBoard/__tests__/index.test.js:154:8)
```

**Expected behavior**
it can simulate click event success

**Screenshots**

**Additional context**
```js
import React from 'react';
import {shallow, mount} from 'enzyme';
import {KeyBoard} from '../../index';

describe('render <KeyBoard/>', () => {
  it('test render div with classnamed .deer-keyboard-input', () => {
    const wrapper = shallow(<KeyBoard count={6} />);
    expect(wrapper.find('.deer-keyboard-input').length).toBe(6);
  });

  it('test render props with active', () => {
    const wrapper = shallow(<KeyBoard active={true} />);
    expect(wrapper.props().className).toBe('mask');
  });

  it('test span click', () => {
    const props = {
      onFinish: jest.fn(),
    };
    const wrapper = mount(<KeyBoard {...props} />);
  
    wrapper
      .find('.deer-keyboard-row')
      .first()
      .childAt(0)
      .simulate('click', {
        target: {
          textContent: 2,
        },
        currentTarget: {},
      });

    //   .find('.deer-keyboard-row')
    //   .at(0)
    //   .childAt(0)
    //   .props()
    //   .onClick();
    // expect(props.onFinish).toBeCalled();
  });
});

```
```jsx
import React from 'react';
import propTypes from 'prop-types';
import classnames from 'classnames';
import './index.less';

class KeyBoard extends React.Component {
  static defaultProps = {
    active: false,
    count: 4,
    autoFinish: false,
  };

  static getDerivedStateFromProps(nextProps, prevState) {
    if (!nextProps.active) {
      return {values: []};
    }
    return null;
  }

  state = {values: []};

  classname = (className, field) => {
    return classnames('deer-keyboard', className, field);
  };

  maskClick = ({target, currentTarget}) => {
    if (target === currentTarget) this.props.onClose();
  };

  renderInput = () => {
    const {values} = this.state;
    const {count} = this.props;
    const input = [];
    for (let i = 0; i < count; ++i) {
      if (i < values.length) {
        input.push(
          <div className="deer-keyboard-input" key={i}>
            <div className="deer-keyboard-input-dot" />
          </div>
        );
      } else {
        input.push(<div className="deer-keyboard-input" key={i} />);
      }
    }
    return input;
  };

  renderRow = () => {
    return Array(3)
      .fill()
      .map((_, i) => {
        return (
          <div className="deer-keyboard-row" key={i}>
            <span>{i * 3 + 1}</span> // this element is that I want want to simulate click event 
            <span>{i * 3 + 2}</span> // when it clicked, the function getValue will be called
            <span>{i * 3 + 3}</span>
          </div>
        );
      });
  };

  getValue = ({target}) => {
    const {count, autoFinish} = this.props;
    const {values} = this.state;
    const value = parseInt(target.textContent);
    if (!isNaN(value)) {
      if (values.length < count) {
        this.setState({values: [...values, value]});
        if (values.length === count - 1) {
          setTimeout(() => {
            this.props.onFinish([...values, value]);
          }, 100);
          if (autoFinish) this.setState({focus: false});
        }
      }
    } else if (target.textContent === 'cancel') {
      this.props.onClose();
    } else {
      if (values.length > 0) {
        this.setState({values: values.slice(0, -1)});
      }
    }
  };

  render() {
    const {className, active, title} = this.props;
    return (
      <div className={classnames({mask: active})} onClick={this.maskClick}>
        <div
          className={this.classname(className, {
            'deer-keyboard-active': active,
          })}
        >
          <div className="deer-keyboard-title">{title}</div>
          <div className="deer-keyboard-input-wrapper">{this.renderInput()}</div>
          <div className="deer-keyboard-button-wrapper" onClick={this.getValue}>
            {this.renderRow()}
            <div className="deer-keyboard-row">
              <span>cancel</span>
              <span>0</span>
              <span>delete</span>
            </div>
          </div>
          <div />
        </div>
      </div>
    );
  }
}

export default KeyBoard;
```

**Comment by ljharb** [comment]
Does this work with v1.4 of enzyme-adapter-react-16, and/or with enzyme v3.5?

**Comment by xuan45** [comment]
@ljharb wow! when I degrade to v1.4 of enzyme-adapter-react-16 and with enzyme v3.5, it can be works well, this may be a bug?

**Comment by ljharb** [comment]
@xuan45 that's likely the case. If you could try 1.4 of the adapter with 3.6 of enzyme, and 1.5 of the adapter with 3.5 of enzyme, that would narrow down exactly what the problem is :-)

**Comment by xuan45** [comment]
@ljharb but I got another problem, when getValue called, state can not update, I try to use wrapper.update. it still can not work
