### ISSUE TITLE
Testing render method

### ISSUE THREAD

**Issue by liricy** [airbnb/enzyme#1848]
I couldn't find any information on this, if this is a duplicate excuse me for stealing your time.

I'm trying to test this application, but I ran into a wall when testing component methods. As an example, take this component:

class TitleContainer extends React.Component {
private isPageEnabled: boolean = false;
private isSubmitter: boolean = false;
  render() {
    return (
            <div>
              {this.isPageEnabled && this.isSubmitter &&
                <div>
                  <br />
                  <SubmitAppFormContainer />
                </div>
              }    
            </div>
  }
}

How could I test the render method here?

**Comment by ljharb** [comment]
```jsx
const wrapper = shallow(<TitleContainer />);
expect(wrapper.find(SubmitAppFormContainer)).to.have.lengthOf(0);
```

You can't really test anything else, since "isPageEnabled" is never anything but `false` in your code.

**Comment by liricy** [comment]
Thanks for your response. But, I'm updating the value of isPageEnabled in ComponentWillUpdate:

![image](https://user-images.githubusercontent.com/6519992/46309973-daa52600-c572-11e8-8fa5-7fa2b37f77c3.png)

**Comment by ljharb** [comment]
If it's a prop, absolutely. You have it marked as "private".

**Comment by liricy** [comment]
Thank you. I get this error on adding test though:

![image](https://user-images.githubusercontent.com/6519992/46310266-c3b30380-c573-11e8-9c8a-4833fc94a101.png)

![image](https://user-images.githubusercontent.com/6519992/46310300-d75e6a00-c573-11e8-84ce-b06e3e876042.png)

**Comment by ljharb** [comment]
The first one is a typescript error and is unrelated to enzyme; the second one is troubling and might reflect a real bug in enzyme.

**Comment by ljharb** [comment]
Also, which exact version of enzyme, react, and the react 15 adapter are you using?

**Comment by liricy** [comment]
Please see code in TitleContainer component:

[TitleContainer.txt](https://github.com/airbnb/enzyme/files/2436096/TitleContainer.txt)

Versions:
"enzyme": "3.3.0",
"enzyme-adapter-react-15": "1.0.6",
"react": "15.6.2"

I replaced test with:

const wrapper = shallow(<TitleContainer {...props} />);
 expect(wrapper.find(SubmitAppFormContainer)).toHaveLength(0);

I still see the following error:

 Enzyme Internal Error: unknown composite type undefined

      at compositeTypeToNodeType (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:63:13)
      at Object.getNode (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:270:27)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:121:46)
      at Object.shallow (node_modules/enzyme/build/shallow.js:19:10)
      at Object.<anonymous> (src/webparts/publishApps/tests/UserRoles.test.tsx:38:34)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ljharb** [comment]
So in that error, what is on line 38 of `UserRoles.test.tsx`?

**Comment by liricy** [comment]
const wrapper = shallow(<TitleContainer {...props} />);

**Comment by liricy** [comment]
[UserRoles.txt](https://github.com/airbnb/enzyme/files/2436126/UserRoles.txt)

Here is my test file

**Comment by ljharb** [comment]
and while I have you, if you delete the `connect` wrapper, and also delete all the methods but `render` in `TitleContainer`, do you get the same issue?

**Comment by liricy** [comment]
Sorry I didn't understand. You mean remove const wrapper = shallow(<TitleContainer {...props} />);?

**Comment by ljharb** [comment]
no, i mean in the actual implementation of `TitleContainer` - reduce it down to just what you have in the OP.

**Comment by liricy** [comment]
I updated the class to:

export class TitleContainer extends React.Component<IConnectedState & IConnectedDispatch & ITitleContainerProps, {}> {
  private isPageEnabled: boolean = false;
  private userRolesErrorMessage: string = "";
  private isSubmitter: boolean = false;
  private isReviewer: boolean = false;
  public render(): React.ReactElement<IConnectedState & IConnectedDispatch> {
    return (
            <div>
              
              {this.isPageEnabled && this.isSubmitter &&
                <div>
                  <br />
                  <SubmitAppFormContainer />
                </div>
              }   
                               
            </div>
    );
  }

Still I get the same error.  On replacing shallow with mount, the test passed.

**Comment by ljharb** [comment]
Thanks - I'm having trouble reproducing this; can you try updating to `enzyme-adapter-react-15` v1.1, and enzyme v3.6?

**Comment by liricy** [comment]
ok will try that. I have a question regrading one of your previous comments. If I update the variables isPageEnabled && isSubmitter to public: 

public isPageEnabled: boolean = false;
public isSubmitter: boolean = false;

Can I set value of this.isPageEnabled & this.isSubmitter to true in the test and expect SubmitAppFormContainer length to equal to 1?

**Comment by ljharb** [comment]
If you set them to true before creating the wrapper, yes.

**Comment by liricy** [comment]
Cool. Will try these 2 tomorrow and let you know. Thanks!

**Comment by ljharb** [comment]
In your case, where you've declared "private" (altho fully public) own properties, you're right - you'd need to alter them, and then `wrapper.update()`, and then you'd be able to `wrapper.find`.

**Comment by liricy** [comment]
Thanks for your response.

I updated code as follows:

```
export class TitleContainer extends React.Component<IConnectedState & IConnectedDispatch & ITitleContainerProps, {}> {
  public isPageEnabled: boolean = false;
  public isSubmitter: boolean = false;
  public render(): React.ReactElement<IConnectedState & IConnectedDispatch> {
    return (
            <div>              
              {this.isPageEnabled && this.isSubmitter &&
                <div>
                  <br />
                  <SubmitAppFormContainer />
                </div>
              }                                  
            </div>
    );
  }
```

And should I update test as follows:

const wrapper = shallow(<TitleContainer {...props} />);
const instance = wrapper.instance() as ListSubmissionsComponent;
instance.isPageEnabled = true;
instance.isSubmitter = true;
wrapper.update();
expect(wrapper.find(SubmitAppFormContainer)).to.have.lengthOf(1);

Please let me know if this is right?

**Comment by ljharb** [comment]
It seems right to me.

**Comment by liricy** [comment]
I tried the same it failed with the error:

![image](https://user-images.githubusercontent.com/6519992/46357395-9f116700-c619-11e8-8ac5-057432b28889.png)

**Comment by liricy** [comment]
I tried one more method. I changed those variables to state variables and here is my updated code:

```
export default class TitleComponent extends React.Component<ITitleProps, ITitleState> {

  public constructor(props: ITitleProps) {
    super(props);

    this.state = {
      isPageEnabled: this.props.isPageEnabled,
      userRolesErrorMessage: this.props.userRolesErrorMessage,
      isSubmitter: this.props.isSubmitter,
      isReviewer: this.props.isReviewer
    };
  }

  public render(): React.ReactElement<ITitleProps> {
    return (
      <div> 
        {this.state.userRolesErrorMessage &&
          <div>
            <br />
            <SubmitAppFormContainer />
          </div>
        }                       
      </div>
    );
  }  
}
```

And the test is:

```
describe("<TitleComponent />", () => {

     const props: ITitleProps = {      
        isPageEnabled: false,
        userRolesErrorMessage: "xyz",
        isSubmitter: false,
        isReviewer: false
    };

    it("should not render ListSubmissionsContainer and SubmitAppFormContainer on page load", () => {
        const reactComponent = mount(<TitleComponent {...props} />);
        expect(reactComponent.find(SubmitAppFormContainer)).toHaveLength(1);
        reactComponent.unmount();
    });    

});
```

And I get a different error:

![image](https://user-images.githubusercontent.com/6519992/46366257-6da39600-c62f-11e8-9de4-dead9c508ace.png)

**Comment by liricy** [comment]
@ljharb b/w I tried updating to enzyme-adapter-react-15 v1.1, and enzyme v3.6 and still using shallow gave me the error:

![image](https://user-images.githubusercontent.com/6519992/46366815-e8b97c00-c630-11e8-9d03-6e5828511f67.png)

**Comment by ljharb** [comment]
I'm not sure how to proceed here. Is there any chance you could make a small repo that can reproduce the problem, so I can clone it myself? That way I can much more easily figure out exactly what is wrong.

**Comment by liricy** [comment]
@ljharb Please let me know if you can access code from this link:

https://microsoftit.visualstudio.com/OneITVSO/_git/EUS-Col-ColPub-PublishApps?version=GBusers%2Flipalath%2Fgithub-code&_a=contents

**Comment by ljharb** [comment]
Note that `npm ls` has to exit successfully, otherwise your dependency graph is invalid, and nothing can be expected to work.

**Comment by liricy** [comment]
Thanks!
