### ISSUE TITLE
TypeError: r is not a function

### ISSUE THREAD

**Issue by capaj** [airbnb/enzyme#2003]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

### Current behavior

```
    TypeError: r is not a function

      13 |     }
      14 |   ]
    > 15 |   const el = mount(
         |              ^
      16 |     <ManageScormPage
      17 |       topic={{
      18 |         workspace_id: 1,

      at t.children (node_modules/react-dropzone/src/index.js:391:12)
      at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14391:31)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14346:24)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15213:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18780:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18820:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18903:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19800:7)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:19712:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19686:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:19555:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:19364:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:20032:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:20060:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:20117:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:20413:3)
      at node_modules/react-dom/cjs/react-dom.development.js:20550:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19915:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:20546:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:20615:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:367:114)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Suite.<anonymous> (front-end/src/pages/manage-scorm-page/ManageScormPage.spec.js:15:14)
      at Object.describe (front-end/src/pages/manage-scorm-page/ManageScormPage.spec.js:8:1)
```

### Expected behavior
no type error
#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 16.8.0
| react-dom           | 16.8.0
| react-test-renderer | 16.8.0
| adapter (below)     |  1.9.1

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by capaj** [comment]
oh this is in react-dropzone, sorry
