### ISSUE TITLE
16.8 (react-test-renderer) causing build failures

### ISSUE THREAD

**Issue by varunsharma27** [airbnb/enzyme#2005]
So react-test-renderer (Dependency of enzyme-adapter-react-16@1.7.1) had a minor release 6 hours ago. Causing our builds to fail all over. We have explicitly added react-test-renderer@16.7.0 in our devDependencies to circumvent that.

```
Running "test:jest" task
[D] Task source: tasks/test_jest.js
 FAIL  ui_framework/components/form/check_box/check_box_label.test.js
  ● KuiCheckBoxLabel › Props › onChange › is called when checkbox is changed

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/form/check_box/check_box_label.test.js:86:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  ui_framework/components/form/check_box/check_box.test.js
  ● KuiCheckBox › Props › onChange › is called when checkbox is changed

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/form/check_box/check_box.test.js:75:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  ui_framework/components/button/button.test.js
  ● KuiButton › Props › onClick › isn't called upon instantiation

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/button/button.test.js:104:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● KuiButton › Props › onClick › is called when the button is clicked

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/button/button.test.js:114:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  ui_framework/components/button/submit_button.test.js
  ● KuiSubmitButton › Props › onClick › isn't called upon instantiation

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/button/submit_button.test.js:65:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● KuiSubmitButton › Props › onClick › is called when the button is clicked

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.test (ui_framework/components/button/submit_button.test.js:75:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  src/core_plugins/metrics/public/components/vis_types/gauge/vis.test.js
  ● renders

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/components/vis_types/gauge/vis.test.js:97:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  src/core_plugins/metrics/public/components/icon_select.test.js
  ● renders

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/components/icon_select.test.js:6:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  src/core_plugins/metrics/public/visualizations/components/vertical_legend.test.js
  ● legend renders: right

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/vertical_legend.test.js:8:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● legend renders: left

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/vertical_legend.test.js:16:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● Click works.

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/vertical_legend.test.js:25:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● onToggle works.

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/vertical_legend.test.js:35:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  src/core_plugins/metrics/public/visualizations/components/legend.test.js
  ● legend vertical

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/legend.test.js:8:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● legend horizontal

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/legend.test.js:16:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 FAIL  src/core_plugins/metrics/public/visualizations/components/horizontal_legend.test.js
  ● horizontal legend renders

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/horizontal_legend.test.js:8:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● Click works.

    TypeError: Cannot read property 'current' of undefined
      
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:703:53)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:460:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:143:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:459:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:206:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous>.test (src/core_plugins/metrics/public/visualizations/components/horizontal_legend.test.js:17:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)


```

**Comment by vzaidman** [comment]
+1

**Comment by yongzhihuang** [comment]
+1

**Comment by erick2014** [comment]
LoL I have the same issue

**Comment by erick2014** [comment]
Hey We found a solution, which was: 
1. update `"enzyme-adapter-react-16": "1.1.0"` to `"enzyme-adapter-react-16.3": "1.6.1"`,
2. within your enzymeSetup change `import Adapter from 'enzyme-adapter-react-16` to Adapter from `enzyme-adapter-react-16.3`

**Comment by varunsharma27** [comment]
However, we are using react 16.7.0, so `enzyme-adapter-react-16.3` would just raise eyebrows. So explicitly adding react-test-renderer@16.7.0 to devDependencies is another option.

**Comment by mountwill** [comment]
I resolved this by upgrading react, react-dom, react-test-renderer to 16.8.1

**Comment by ljharb** [comment]
@varunsharma27 first, you're not using the latest version of your react adapter. Please update to the latest.

Can you confirm - if you have the latest `enzyme`, `enzyme-adapter-react-16`, `react`, and `react-dom` (and if you have a lockfile, that `react-test-renderer` is also updated to 16.8), do you still see issues?

**Comment by c0d3x** [comment]
Have same issue when running tests with react 16.8, works fine in 16.7.

**Comment by varunsharma27** [comment]
@ljharb We are using :- 
enzyme: 3.8.0
enzyme-adapter-react-16: ^1.7.1 -> 1.9.1
react: 16.7
react-dom: 16.7

The issue is created because a release in react-test-renderer caused build failures for us, which we do not directly rely upon.

As per @c0d3x, react 16.8 and enzyme 1.9.1 are having the same issue.

**Comment by ljharb** [comment]
@varunsharma27 yes, that's unfortunately the nature of semver here. I'm not sure how to fix it in enzyme cleanly; but you can add `react-test-renderer@~16.7` as a dev dep to fix it.

**Comment by varunsharma27** [comment]
Yes, that's exactly what we did to circumvent this issue. And reported it to help others out.

**Comment by mikebm** [comment]
I finally figured out what was causing our problem. I could not reproduce this outside of Jest, but it happened every-time within our applications jest tests. The issue is because we had the following entry in moduleNameMapper jest config:
'lodash.flatten': 'lodash/flatten',

Since these are regex patterns, it caused `lodash.flattendeep` to use 'lodash.flatten' instead. `rst-selector-parser` uses flattendeep in their `grammar.js` file to flatten those arrays.  

Hope this helps someone else.

**Comment by mikebm** [comment]
I was experiencing this same exact issue in only a couple of my tests. I am on the latest 16.8.6 version of react (all the things). I found that what fixed it was changing the import order.

Importing my React Components before my import of `import Adapter from 'enzyme-adapter-react-16';` would result in it breaking. Importing my React Components AFTER importing the adapter worked.

Breaking:
```
import React from 'react';
import Enzyme, { shallow, mount } from 'enzyme';
import { TestComponent } from './test.component';
import Adapter from 'enzyme-adapter-react-16';
```

Working:
```
import React from 'react';
import Enzyme, { shallow, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { TestComponent } from './test.component';
```

**Comment by howdyitshelena** [comment]
Also seeing a lot of failures with React, react-dom & react-test-renderer 16.8.6:

`TypeError: Cannot read property '_reactInternalFiber' of null at getFiber`

Anyone else seeing this?

**Comment by ljharb** [comment]
@howdyitshelena can you file a new issue for that, and include the full stack trace?

**Comment by howdyitshelena** [comment]
@ljharb will do, thank you!

**Comment by GuannanHe** [comment]
I got the same issue, fixed it by update enzyme-adapter-react-16 to 1.12.1
