### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined in setupTest.js

### ISSUE THREAD

**Issue by zhr1130** [airbnb/enzyme#2050]
I am trying to setup enzyme for my typescript react project. But I am getting below error, my test case is pretty simple, just use 'shallow' to test a HelloWorld componet. Any help would be really appreciated ! 

 TypeError: Cannot read property 'split' of undefined

      1 | const Enzyme = require('enzyme');
    > 2 | const Adapter =  require('enzyme-adapter-react-16');
        |                  ^
      3 |
      4 | Enzyme.configure({ adapter: new Adapter() });

      at new Range (node_modules/enzyme-adapter-utils/node_modules/semver/semver.js:800:20)
      at intersects (node_modules/enzyme-adapter-utils/node_modules/semver/semver.js:1334:8)
      at Object.<anonymous> (node_modules/enzyme-adapter-utils/build/wrapWithSimpleWrapper.js:37:39)
      at Object.<anonymous> (node_modules/enzyme-adapter-utils/build/Utils.js:47:30)
      at Object.<anonymous> (node_modules/enzyme-adapter-utils/build/index.js:4:18)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:47:27)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/index.js:4:18)
      at Object.require (setupTests.js:2:18)
          at Array.forEach (<anonymous>)

react: "16.8.4"
react-dom: "16.8.4"
react-test-renderer: "16.8.4"
enzyme: 3.9.0
enzyme-adapter-react-16: 1.11.0
============================================================
jest.config.js:

module.exports = {
    "roots": [
        "<rootDir>/src"
    ],
    "transform": {
        "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
        "^.+\\.tsx?$": "ts-jest",
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
        '<rootDir>/config/jest/assetsTransformer.js'
      },
    "testPathIgnorePatterns": [
        "/node_modules/",
        "/lib/"
    ],
    "testRegex": "(/__tests__/.*(test|spec))\\.(ts|tsx|js)$",
    "testEnvironment": "jsdom",
    "moduleFileExtensions": [
        "ts",
        "tsx",
        "jsx",
        "js",
        "json"
    ],
    "setupFilesAfterEnv": ["<rootDir>/setupTests.js"],
    "snapshotSerializers": ["enzyme-to-json/serializer"],
    "moduleNameMapper": {
        "\\.(js)$": "<rootDir>/src/__mocks__/fileMock.js",
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/__mocks__/fileMock.js",
        "\\.(scss|css|less)$": "<rootDir>/src/__mocks__/styleMock.js"
    },
    "cacheDirectory": "<rootDir>/tmp"
}

**Comment by ljharb** [comment]
The `undefined` being passed in is `React.version` - do you have react actually installed and present on disk?

**Comment by ljharb** [comment]
Note that if `npm ls` does not exit successfully, your dependency graph is invalid, and nothing can be expected to work.

**Comment by zhr1130** [comment]
Thanks @ljharb , I have react installed on my disk. And I can see my component by running 'npm start' and going to localhost:8080. 
I only got one error when running 'npm ls'. 
peer dep missing: react@>= 0.13.0 <16.0.0, required by react-fa@4.2.0.
Does it matter ? I tried upgrade react-fa to 5.0.0, but it still gave me this error.

**Comment by ljharb** [comment]
Yes, that matters - what that means is that react-fa@4.2 requires react below 16; which means your dep graph is invalid.
