### ISSUE TITLE
enzyme adapter giving ERROR in ./~/react-test-renderer/package.json

### ISSUE THREAD

**Issue by MoAli2016** [airbnb/enzyme#2111]
I am getting the following error trace
```
@ ./~/enzyme-adapter-react-16/build/ReactSixteenAdapter.js 27:15-58
25 04 2019 18:29:18.689:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
25 04 2019 18:29:18.691:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
25 04 2019 18:29:18.695:INFO [launcher]: Starting browser ChromeHeadless
25 04 2019 18:29:19.197:INFO [HeadlessChrome 75.0.3738 (Mac OS X 10.14.4)]: Connected on socket dLE05r-TcFi8BxEHAAAA with id 2673721
HeadlessChrome 75.0.3738 (Mac OS X 10.14.4) ERROR
  {
    "message": "Uncaught Error: Cannot find module \"react-test-renderer/package.json\"\nat test/index.js:12553:180\n\nError: Cannot find module \"react-test-renderer/package.json\"\n    at webpackMissingModule (test/index.js:12553:81)\n    at Object.<anonymous> (test/index.js:12553:190)\n    at Object.<anonymous> (test/index.js:13513:31)\n    at __webpack_require__ (test/index.js:20:30)\n    at Object.<anonymous> (test/index.js:12519:19)\n    at __webpack_require__ (test/index.js:20:30)\n    at Object.<anonymous>(test/index.js:53:28)\n    at __webpack_require__ (test/index.js:20:30)\n    at test/index.js:40:18\n    at test/index.js:43:10",
    "str": "Uncaught Error: Cannot find module \"react-test-renderer/package.json\"\nat test/index.js:12553:180\n\nError: Cannot find module \"react-test-renderer/package.json\"\n    at webpackMissingModule (test/index.js:12553:81)\n    at Object.<anonymous> (test/index.js:12553:190)\n    at Object.<anonymous> (test/index.js:13513:31)\n    at __webpack_require__ (test/index.js:20:30)\n  at Object.<anonymous> (test/index.js:12519:19)\n    at __webpack_require__ (test/index.js:20:30)\n    at Object.<anonymous> (test/index.js:53:28)\n    at __webpack_require__ (test/index.js:20:30)\n    at test/index.js:40:18\n    at test/index.js:43:10"
  }
```
when I run karma start. 
"react": "^16.1.0"
"react-dom": "^16.1.0"
"react-test-renderer": "^16.1.0"

I wonder if any can give us a clue on how to resolve this issue. Thanks

**Comment by ljharb** [comment]
This looks like your karma config isn't properly set up to allow JSON requires. Can you share your karma config?

**Comment by MoAli2016** [comment]
Thanks for the quick reply. Here is the karma config
```
const puppeteer = require('puppeteer');
process.env.CHROME_BIN = puppeteer.executablePath();
var webpack = require("webpack");
var path = require("path");

module.exports = function(config) {
  config.set({
    frameworks: ["mocha", "sinon", "chai"],

    browsers: ["ChromeHeadless"],

    singleRun: true,

    files: ["test/index.js"],

    browserConsoleLogOptions: {level: "debug", format: "%b %T: %m", terminal: true},

    preprocessors: {
      "test/index.js": ["webpack"]
    },

    reporters: ["progress"],

    webpack: {
      devtool: "inline-source-map",
      module: {
        loaders: [
          {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: "babel",
            query: {
              presets: ["airbnb"]
            }
          },
          {
            test: /\.jsx?$/,
            include: path.resolve(__dirname, "src"),
            loader: "isparta"
          }
        ]
      }, 
      plugins: [
        new webpack.DefinePlugin({
          "process.env.NODE_ENV": JSON.stringify("test")
        })
      ],
      resolve: {
        extensions: ["", ".jsx", ".js"]
      },
      externals: {
        cheerio: "window",
        "react/addons": true,
        "react/lib/ExecutionEnvironment": true,
        "react/lib/ReactContext": true
      }
    },

    coverageReporter: {
      reporters: [
        { type: "text-summary" },
        { type: "html", dir: "coverage/" },
        { type: "lcov" }
      ]
    },

    webpackServer: {
      noInfo: true
    }
  });
};
```

**Comment by ljharb** [comment]
Add `.json` to your resolve extensions list, since node can require them by default.

**Comment by MoAli2016** [comment]
still have the error. Added
`   resolve: {
        extensions: ["", ".jsx", ".js", ".json"]
      },`

**Comment by ljharb** [comment]
https://stackoverflow.com/a/34847329/632724 seems relevant?

**Comment by MoAli2016** [comment]
Hi @ljharb, I set up the pattern  { pattern: 'test/**/*.json', included: false, served: true} but still the error above persists. However, while running karma start all dependencies are built except one
```
./~/enzyme-adapter-react-16/build/ReactSixteenAdapter.js 92.1 kB {0} [built] [1 error]
```
I did not spotted this earlier.  I guess this causes the error in the title of this post. Thank you for your help

**Comment by MoAli2016** [comment]
I bypassed test/index.js. Just went for the test files directly. I followed this link
https://github.com/webpack-contrib/karma-webpack
and got the tests passing. @ljharb very similar idea to your suggestion above. Added the code below to my karma.config.   
```
 preprocessors: {
//      "test/index.js": ["webpack"] <== removed
      'test/*_test.js': [ 'webpack' ],
      'test/**/*_test.js': [ 'webpack' ]
    },
```
