### ISSUE TITLE
Async await not working while mocking

### ISSUE THREAD

**Issue by viveksanthosh** [airbnb/enzyme#2130]
### Current behavior
My componentDidMount is an async function that looks like this 

 async componentDidMount() {
    await this.runBeforeStart();
    await this.restoreState();
    this.prepareIntents(this.state.customMeta.intents)
  }

runBeforeStart = async () => {
    let { state, props } = this;
}

the test code looks like this

import { mount, shallow } from 'enzyme';
import App from './App';
import React from 'react';

describe('Render the right options', () => {
    const getWrapper = (props) => {
        return mount(<App {...props} />)
    }
    it('should render', async () => {

        let wrapper = getWrapper({ id: 1 });
    })
})

and when i run the test I get this error,

  ● Render the right options › should render

    TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object

      240 |   }
      241 | 
    > 242 |   runBeforeStart = async () => {
          |                            ^
      243 |     let { state, props } = this;
      244 | 
      245 |     let before_starts = props.customMeta.before_start;

      at _callee5$ (src/App.js:242:28)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at App.runBeforeStartFunction (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
      at App.runBeforeStartFunction (src/App.js:322:16)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at App.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
      at App.componentDidMount (src/App.js:2752:35)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17130:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18532:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:18744:7)
      at node_modules/react-dom/cjs/react-dom.development.js:20214:5
      at Object.unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:20213:13)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:20142:9)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:19886:7)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:19707:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:20368:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:20396:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:20453:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:20749:3)
      at node_modules/react-dom/cjs/react-dom.development.js:20886:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:20250:14)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:20882:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:20951:12)
      at render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:418:26)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:342:37)
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:20235:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1161:27)
      at act (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:342:13)
      at Object.wrapAct [as render] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:16)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at getWrapper (src/App.test.js:23:16)
      at getWrapper (src/App.test.js:29:23)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
### Expected behavior
I expect the error not to occur
#### API
 mount

#### Version

| library             | version

| enzyme              |  enzyme@^3.9.0:
| react               |  react@^16.8.0:
| react-dom           |  react-dom@^16.8.0:
| react-test-renderer | jest@^23.6.0:
| adapter (below)     |   enzyme-adapter-react-16

#### Adapter
 enzyme-adapter-react-16

**Comment by ljharb** [comment]
You said “while mocking”; what’s being mocked?

The error is coming from Babel, not enzyme - something with its async/await transpilation. It will happen without enzyme as well.

What does your babelrc look like?

**Comment by OmriGM** [comment]
Hi,
It doesn't look like Enzyme is throwing the error as @ljharb mentioned, if you will provide us the full implementation of `runBeforeStart ` function it will be easier to say where the error is coming from.
Maybe you did not use try/catch, or did not return/throw anything from this function although you are using curly braces with arrow function.

**Comment by ljharb** [comment]
Please do provide the full, *unredacted* code - every single line is potentially needed to be able to understand what went wrong.

**Comment by viveksanthosh** [comment]
Thanks for the quick reply, the reason I suspect that there may be an issue with enzyme is because I tried using React unit(https://www.npmjs.com/package/react-unit) and the above error does not occur, although when I used react-testing-library (https://www.npmjs.com/package/react-testing-library) I faced the exact same issue.

The babel file I am using is https://github.com/jaredpalmer/razzle/blob/master/packages/babel-preset-razzle/index.js, it is part of the razzle (https://github.com/jaredpalmer/razzle) framework.

The complete code of the function is 

 runBeforeStart = async () => {
    let { state, props } = this;

    let before_starts = props.customMeta.before_start;
    for (let before_start of before_starts) {
      let setState = (state) => this.setState(state);
      const updateQuestion = this.updateQuestion;
      if (before_start) {
        try {
          let functionToRun;
          eval("functionToRun = " + before_start); // eslint-disable-line no-eval
          await functionToRun({ state, props, setState, Constants, updateQuestion, capitalizeFirstLetter: this.capitalizeFirstLetter });
        } catch (e) {
          console.log(e);
        }
      }
    }
  }

**Comment by ljharb** [comment]
I’d never heard of react-unit; react-testing-library is just a thin wrapper around the DOM that React already renders, so it’d suffer from a Babel issue like anything else.

Certainly any use of `eval` is abjectly bad code, and you shouldn’t be disabling eslint for it - Babel can’t transpile code you send into eval.

I’m not familiar with razzle either, but it doesn’t seem related. I think it’s probably the eval.
