### ISSUE TITLE
Cannot read property '_reactInternalFiber' of null

### ISSUE THREAD

**Issue by teterin** [airbnb/enzyme#2163]
After updating react version to `16.8.6` I get error:
```
TypeError: Cannot read property '_reactInternalFiber' of null
      at getFiber (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:16:2)
      at detectFiberTags (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:77:5)
      at ReactSixteenAdapter.createMountRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:407:19)
      at ReactSixteenAdapter.createRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:752:51)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:113:32)
      at mount (node_modules/enzyme/src/mount.js:10:10)
```

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This usually happens from a (broken) mock of react-dom

**Comment by JonathanLehner** [comment]
What is a broken mock? I have the same issue. How to solve it?

**Comment by ljharb** [comment]
Don't mock react-dom :-)
