### ISSUE TITLE
mount Suspense and throw promise - Enzyme Internal Error: unknown node with tag 2

### ISSUE THREAD

**Issue by json2d** [airbnb/enzyme#2205]
### Current behavior
Getting error `Enzyme Internal Error: unknown node with tag 2` 

from mounting `Suspense` component with child component that throws promise:

```js
import React, { Suspense } from "react";

const Message = props => <div>Hello Enzyme!</div>
const Loading = props => <div>loading...</div>
const Thrower = props => {
  throw new Promise(resolve => {
    setTimeout(resolve, 1000);
  });
};
describe("integration with Suspense component", () => {
  test("should render Message component", () => {
    const wrapper = mount(
      <Suspense fallback={<Loading />}>
        <Message />
      </Suspense>
    );

    expect(wrapper.find(Message)).toExist(); // ✅ passes
  });

  test("should render Loading component", () => {
    const wrapper = mount(
      <Suspense fallback={<Loading />}>
        <Thrower />
      </Suspense>
    );

    expect(wrapper.find(Loading)).toExist(); // ❌ Enzyme Internal Error: unknown node with tag 2
  });
})
```

trace:
```
    Enzyme Internal Error: unknown node with tag 2

      20 | 
      21 |   test("should render Loading component", () => {
    > 22 |     const wrapper = mount(
         |                     ^
      23 |       <Suspense fallback={<Loading />}>
      24 |         <Thrower />
      25 |       </Suspense>

      at _toTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:254:13)
      at toTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:267:12)
      at childrenToTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:227:14)
          at Array.map (<anonymous>)
      at map (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:269:27)
      at childrenToTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:248:19)
      at toTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:267:12)
      at childrenToTree (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:169:19)
      at Object.toTree [as getNode] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:448:11)
      at new getNode (node_modules/enzyme/src/ReactWrapper.js:117:44)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at Object.mount (__tests__/Suspense.spec.js:22:21)
```

### Expected behavior
No error

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| _jest-enzyme_         | _7.0.2_
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 1.14.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by json2d** [comment]
#1917 #1975

**Comment by ljharb** [comment]
Looks related to #2125.

**Comment by ljharb** [comment]
Does this only occur when you throw a promise, as opposed to another kind of exception?

**Comment by json2d** [comment]
Yep, `throw new Error()` instead of a promise doesn't yield this kind of message

**Comment by ljharb** [comment]
So you're not using any `React.lazy` components - which have to be [a promise](https://reactjs.org/docs/code-splitting.html#reactlazy) for an object with a `default` property that's a React component - but I'm not sure you're supposed to be *able* to throw a promise directly inside Suspense.

Can you link me to the React docs that talk about this? https://reactjs.org/docs/code-splitting.html doesn't seem to.

**Comment by json2d** [comment]
Throwing a promise should be the other valid way to implement an async component - afaik.

here's a pretty recent article that talks about it:
https://blog.logrocket.com/the-future-of-react-unfolding-with-suspense/

**Comment by ljharb** [comment]
hmm, in that case perhaps the "thrown promise" case isn't something we're handling properly.

**Comment by CrOrc** [comment]
Throwing promise inside render is supported by React Suspense.
See pull request in React repo [Accept promise as element type](https://github.com/facebook/react/pull/13397)

**Comment by OlgaKuksa** [comment]
Hi there, is there any update on the issue? Looking forward for it to be fixed!

**Comment by jeffersoneagley** [comment]
Still broken?

**Comment by nickpalmer** [comment]
[react-lazy-ssr](https://github.com/overlookmotel/react-lazy-ssr) triggers this error because it throws a promise.

While there is a workaround, it would be nice if Enzyme supported it without the workaround.

**Comment by rdy** [comment]
I also ran into this issue testing recoil with enzyme and using a value that returns a promise. 

It would be nice to be able to use suspense with enzyme.

**Comment by ljharb** [comment]
I'm working on fixing this, but the "detect fiber tags" code we use is having trouble figuring out the 17 (it has to be done dynamically so it doesn't break over time).

**Comment by artola** [comment]
@ljharb I found this problem using v1.15.6 of the adapter. I am using `relay v11` with `relay-test-utils`. Do you have some hint?

**Comment by ljharb** [comment]
@artola i can reproduce the issue, but i can't figure out yet how to update our internals to handle it.

**Comment by artola** [comment]
> @artola i can reproduce the issue, but i can't figure out yet how to update our internals to handle it.

I will give it a try. Thanks.

**Comment by artola** [comment]
@ljharb I did some changes and it seems to work for me (at least my test is working), but I have not your experience and broad vision. Does it makes some sense?

```js
// detectFiberTags.js
...
  function LazyFn() {
    throw Promise.resolve();
  }
...
module.exports = function detectFiberTags() {
...
  return {
    FunctionalComponentLazy: supportsLazy ? getLazyFiber(LazyFn).tag : -1,
```

```js
// reactSixteenAdapter.js
...
    case FiberTags.Lazy:
    case FiberTags.FunctionalComponentLazy:
      return childrenToTree(node.child);
```

There is also a `ClassComponentLazy` that should be supported.

**Comment by ljharb** [comment]
@artola if you can make a PR with passing tests, then that sounds awesome.

**Comment by totszwai** [comment]
Failing without any async nor Promise.

```
it('blah', () => {
  const wrapper = render(
      <I18nextProvider i18n={i18n}>
        <Suspense fallback="Loading...">
          <Test />
        </Suspense>
      </I18nextProvider>
  );

  console.log(wrapper.debug());
});
```

> Enzyme Internal Error: unknown node with tag 2
