### ISSUE TITLE
cant working with react 16

### ISSUE THREAD

**Issue by yanxiaosong0902** [airbnb/enzyme#2315]
### setup.js
```javascript
var Enzyme = require('enzyme')
var Adapter = require('enzyme-adapter-react-16')
Enzyme.configure({ adapter: new Adapter() })
```
When I run jest, it got this error:
```
TypeError: Cannot read property 'Events' of undefined

 at node_modules/react-dom/cjs/react-dom-test-utils.development.js:848:89
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1301:5)
      at Object.<anonymous> (node_modules/react-dom/test-utils.js:6:20)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:29:18)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/index.js:4:18)
      at Object.<anonymous> (test/setup.js:4:15)
```
where the `Events` found  here
```
var _ReactDOM$__SECRET_IN = ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.Events;
```
### Version
```json
"react": "~16.8.6",
"react-dom": "~16.8.6",
"enzyme": "^3.10.0"
"jest": "^24.5.0",
"enzyme-adapter-react-16": "^1.15.2"
```

**Comment by ljharb** [comment]
Did you figure it out?
