### ISSUE TITLE
Error: This method is only meant to be run on single node. 0 found instead.

### ISSUE THREAD

**Issue by andresgallego** [airbnb/enzyme#265]
Hello, I'm testing a React component as follows:

```
test('CardPlayer', assert => {
  const msg = 'CardPlayer should render something.';
  const CardPlayer = cardPlayer(React);
  const courseTitle = 'My Course';

  const props = {
    courseTitle
  };

  const $ = shallow(<CardPlayer { ...props } />);
  const output = $.find('.course-title').html();

  const re = new RegExp(courseTitle, 'g');
  const actual = re.test(output);
  const expected = true;

  assert.equal(actual, expected, msg);

  assert.end();
});
```

And my component:

```
export default React => ({ courseTitle }) => (
  <h1 className="course-title">{ courseTitle }</h1>
);
```

But I'm getting this error:

``
throw new Error('This method is only meant to be run on single node.
                ^
Error: This method is only meant to be run on single node. 0 found instead.
    at ShallowWrapper.single (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/enzyme/build/ShallowWrapper.js:1092:17)
    at ShallowWrapper.html (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/enzyme/build/ShallowWrapper.js:443:21)
    at Test.<anonymous> (App.js:54:42)
    at Test.bound [as _cb] (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/tape/lib/test.js:80:10)
    at Test.bound [as run] (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/tape/lib/test.js:61:32)
    at Object.next [as _onImmediate] (/Users/andrescavs/Development/Projects/coupleville/react-pure-component-starter/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
``

Any help please?

**Comment by ljharb** [comment]
Your test is trying to find `.course-title` - but your component's *root* node is the one with that class. I think you just want `$.html()` directly.

**Comment by andresgallego** [comment]
It works, thanks a lot!
