### ISSUE TITLE
Tests break with React 15.0.1

### ISSUE THREAD

**Issue by tgoldenberg** [airbnb/enzyme#315]
This is my output from `npm test`. I am running a `meteor 1.3` app with a React frontend - ` Cannot read property 'listenTo' of undefined
    at Object.<anonymous> (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/react/lib/ReactDOMComponent.js:50:40)
    at Loader._execModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:207:17)
    at Loader.requireModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:761:14)
    at Loader.requireModuleOrMock (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:791:19)
    at Object.<anonymous> (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/react/lib/ReactDefaultInjection.js:21:25)
    at Loader._execModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:207:17)
    at Loader.requireModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:761:14)
    at Loader.requireModuleOrMock (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:791:19)
    at Object.<anonymous> (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/react/lib/ReactDOM.js:17:29)
    at Loader._execModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:207:17)
    at Loader.requireModule (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:761:14)
    at Loader.requireModuleOrMock (/Users/thomasgoldenberg/Desktop/agolo/test-agolo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:791:19)
`

**Comment by ljharb** [comment]
Can you share the code of the component being tested, and the test code that's failing? Also, please make sure you're mocking the right things for jest https://github.com/airbnb/enzyme/blob/master/docs/guides/jest.md

**Comment by tgoldenberg** [comment]
@ljharb My tests were running find previous to this. Here is a sample test, and my package.json
`import React from 'react';
import ReactDOM from 'react-dom';
import TestUtils from 'react-addons-test-utils';
import {shallow} from 'enzyme';

jest.dontMock('../cluster_score.jsx');
jest.dontMock('../../utilities/feed_utilities');

const ClusterScore = require('../cluster_score.jsx');
const getScore = require('../../utilities/feed_utilities').getScore;

describe('getScore', () => {
  it('renders the correct score with props', () => {
    const wrapper = shallow(
      <ClusterScore maxScore={1} score={0.5} />
    )
    expect(wrapper.text()).toBe('Relevancy: 50%')
  })
  it('renders a score of 0 with no props', () => {
    const wrapper = shallow(
      <ClusterScore />
    )
    expect(wrapper.text()).toBe('Relevancy: 0%');
  })
})`

`
  "name": "test-agolo",
  "version": "1.0.0",
  "description": "agolo",
  "main": "test-agolo.js",
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "setupEnvScriptFile": "<rootDir>/.scripts/setup-jest-tests.js",
    "testRunner": "<rootDir>/node_modules/jest-cli/src/testRunners/jasmine/jasmine2.js",
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "preprocessCachingDisabled": "true",
    "testPathDirs": [
      "<rootDir>/client/modules",
      "<rootDir>/tests/__mocks__"
    ],
    "testDirectoryName": "client/modules",
    "testFileExtensions": [
      "tests.js",
      "tests.jsx"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json",
      "node"
    ],
    "unmockedModulePathPatterns": [
      "underscore/.*",
      "core-js/.*",
      "babel-runtime/.*",
      "react/.*",
      "react-dom/.*",
      "fbjs/.*",
      "react-addons-test-utils/.*",
      "enzyme/*"
    ]
  },
  "devDependencies": {
    "babel-core": "^6.3.17",
    "babel-jest": "^6.0.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.2.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.4.0",
    "babel-plugin-transform-runtime": "^6.3.13",
    "babel-plugin-transform-strict-mode": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "classnames": "^2.2.1",
    "enzyme": "^2.2.0",
    "jasmine": "https://github.com/xolvio/jasmine-npm/archive/29065151846755d6bbad369f506143ebf69b168f.tar.gz",
    "jest-cli": "Sanjo/jest#7c71094",
    "json-loader": "^0.5.4",
    "karma": "^0.13.16",
    "karma-chrome-launcher": "^0.2.2",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.6",
    "karma-sourcemap-loader": "0.3.6",
    "karma-webpack": "1.7.0",
    "phantomjs": "^1.9.19",
    "react-addons-test-utils": "^15.0.1",
    "shelljs": "^0.5.3",
    "underscore": "^1.8.3",
    "velocity-cli": "^0.4.3",
    "wallaby-webpack": "0.0.10",
    "webpack": "^1.12.9"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-plugin-transform-class-properties": "^6.4.0",
    "classnames": "^2.2.3",
    "d3": "^3.5.16",

    "jquery": "^2.2.0",
    "moment": "^2.11.1",
    "radium": "^0.16.6",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.1",
    "react-addons-pure-render-mixin": "^15.0.1",
    "react-addons-shallow-compare": "^15.0.1",
    "react-bootstrap": "^0.28.3",
    "react-dom": "^15.0.1",
    "react-icons": "^1.0.3",
    "react-input-range": "^0.6.1",
    "react-loading": "0.0.7",
    "react-mixin": "^2.0.2",
    "react-motion": "^0.4.2",
    "react-motion-ui-pack": "^0.6.0",
    "react-router": "^2.0.0-rc4",
    "react-selectize": "https://github.com/tgoldenberg/react-selectize/tarball/add_js",
    "react-tooltip": "^1.1.4",
    "react-transform-hmr": "^1.0.2",
    "stock-data": "^0.1.0",
    "tether": "^1.2.0",
    "underscore.string": "^3.2.2"
  }
}`

**Comment by tgoldenberg** [comment]
Here's the component - 
```
import React from 'react';
import {getScore,} from '../utilities/feed_utilities';

class ClusterScore extends React.Component{
  render(){
    return (
      <span className="m-l-1"><b>Relevancy:</b> {getScore(this.props.score, this.props.maxScore)}%</span>
    )
  }
}

ClusterScore.propTypes = {
  score: React.PropTypes.number.isRequired,
  maxScore: React.PropTypes.number.isRequired,
}
ClusterScore.defaultProps = {
  score : 0,
  maxScore: 0,
}

module.exports = ClusterScore;
```

**Comment by andrewmclagan** [comment]
also the same issue

**Comment by andrewmclagan** [comment]
arrrhh..? no...?

**Comment by tgoldenberg** [comment]
@andrew, So I adjusted my package.json and basically started from scratch. Here is the new `package.json` that I am using and getting most of the tests most of the time ;) to pass. 

```
  "name": "test-agolo",
  "version": "1.0.0",
  "description": "agolo",
  "main": "test-agolo.js",
  "scripts": {
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "babel": {
    "env": {
      "production": {
        "plugins": [
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      }
    }
  },
  "jest": {
    "setupEnvScriptFile": "<rootDir>/.scripts/setup-jest-tests.js",
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "testPathDirs": [
      "<rootDir>/client/modules"
    ],
    "testDirectoryName": "client/modules",
    "testFileExtensions": [
      "tests.js",
      "tests.jsx"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json",
      "node"
    ],
    "unmockedModulePathPatterns": [
      "underscore/.*",
      "core-js/.*",
      "babel-runtime/.*",
      "react/.*",
      "react-dom/.*",
      "fbjs/.*",
      "react-addons-test-utils/.*",
      "enzyme/.*"
    ]
  },
  "dependencies": {
    "bootstrap": "^4.0.0-alpha.2",
    "btoa": "^1.1.2",
    "classnames": "^2.2.3",
    "d3": "^3.5.16",
    "jquery": "^2.2.3",
    "moment": "^2.13.0",
    "radium": "^0.17.1",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.1",
    "react-addons-pure-render-mixin": "^15.0.1",
    "react-addons-shallow-compare": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-icons": "^2.0.1",
    "react-input-range": "^0.6.2",
    "react-loading": "0.0.9",
    "react-motion": "^0.4.2",
    "react-motion-ui-pack": "^0.7.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.2.4",
    "react-selectize": "https://github.com/tgoldenberg/react-selectize/tarball/add_js",
    "react-tooltip": "^1.2.0",
    "redux": "^3.4.0",
    "underscore": "^1.8.3",
    "underscore.string": "^3.2.2"
  }
}
```

**Comment by tgoldenberg** [comment]
and no, not using karma

**Comment by dsifford** [comment]
@tgoldenberg How about a more helpful explanation of what you did to solve your issue? I'm also running jest and having similar problems.

**Comment by tgoldenberg** [comment]
@dsifford  Basically, I gutted my package.json and started from scratch. I shared the `package.json` during the problems and after. That's about it for changes. My setup script and everything else stayed the same. A lot of packages were relying on previous version of react `^0.014.0`, etc., so gutting my `node_modules` directory, and building it up from scratch was the painful, but effective way of getting the tests to work again. Hope this is helpful

**Comment by dsifford** [comment]
@tgoldenberg Ah, that's disappointing. Hoped you might have had an easier solution.

@andrewmclagan This issue happens for me when I attempt to pass an array of objects as a prop. Is this a known issue?

**Comment by dsifford** [comment]
@andrewmclagan Example: 

```ts
const spy = sinon.spy();
        const wrapper = mount(
            <People citationType='article' eventHandler={spy} people={[{ type: 'author', family: 'asdfadsfasd', given: 'asdfasdf'}]} />
        );
```

```sh
        at QueueRunner.clearStack (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:607:9)                               [23/1828]
        at QueueRunner.run (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1786:12)                                    [22/1828]
        at QueueRunner.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1764:10)                                [21/1828]
        at Spec.Env.queueRunnerFactory (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:629:35)                         [20/1828]
        at Spec.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:355:10)                                        [19/1828]
        at Object.fn (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:2362:37)                                          [18/1828]
        at attemptAsync (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1821:24)                                       [17/1828]
        at QueueRunner.run (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1776:9)                                     [16/1828]
        at QueueRunner.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1764:10)                                [15/1828]
        at Env.queueRunnerFactory (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:629:35)                              [14/1828]
        at Object.fn (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:2347:13)                                          [13/1828]
        at attemptAsync (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1821:24)                                       [12/1828]
        at QueueRunner.run (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1776:9)                                     [11/1828]
        at QueueRunner.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1764:10)
        at Env.queueRunnerFactory (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:629:35)
        at TreeProcessor.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:2211:7)
        at Env.execute (node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:680:17)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:194:7)
        at handle (node_modules/worker-farm/lib/child/index.js:41:8)
        at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
        at emitTwo (events.js:100:13)
        at process.emit (events.js:185:7)
        at handleMessage (internal/child_process.js:718:10)
        at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by dsifford** [comment]
Gonna open a new issue on this since it's totally crippling my productivity right now.
