### ISSUE TITLE
.is with constructor/displayName selector does not work when shallowly rendered

### ISSUE THREAD

**Issue by ahstro** [airbnb/enzyme#628]
According to your documentation [`.is` should work with shallow wrappers](http://airbnb.io/enzyme/docs/api/ShallowWrapper/is.html), but that doesn't seem to be the case for me when using the constructor or display name as the selector (it still works if I'm using a CSS selector). Using `mount` solves this, but that means that either I'm doing something wrong, there's a bug in your docs, or there's a bug in your code (in that order of likelyhood, I assume).

### Tests
```js
import React, { Component } from "react"
import { expect } from "chai"
import { mount, shallow } from "enzyme"

class MyClass extends Component {
  render() {
    return <div className="foobar">Foo</div>
  }
}

const MyFunction = () => <div className="foobar">Foo</div>

describe("Broken enzyme thing", () => {

  it("works with shallow classes and constructor", function() {
    expect(shallow(<MyClass />).is(MyClass)).to.be.true
  })

  it("works with shallow classes and display name", function() {
    expect(shallow(<MyClass />).is("MyClass")).to.be.true
  })

  it("works with shallow classes and class name", function() {
    expect(shallow(<MyClass />).is(".foobar")).to.be.true
  })

  it("works with shallow functions and constructor", function() {
    expect(shallow(<MyFunction />).is(MyFunction)).to.be.true
  })

  it("works with shallow functions and display name", function() {
    expect(shallow(<MyFunction />).is("MyFunction")).to.be.true
  })

  it("works with shallow functions and class name", function() {
    expect(shallow(<MyFunction />).is(".foobar")).to.be.true
  })

  it("works with mount classes and constructor", function() {
    expect(mount(<MyClass />).is(MyClass)).to.be.true
  })

  it("works with mount classes and display name", function() {
    expect(mount(<MyClass />).is("MyClass")).to.be.true
  })

  it("works with mount classes and class name", function() {
    expect(mount(<MyClass />).is(".foobar")).to.be.true
  })

  it("works with mount functions and constructor", function() {
    expect(mount(<MyFunction />).is(MyFunction)).to.be.true
  })

  it("works with mount functions and display name", function() {
    expect(mount(<MyFunction />).is("MyFunction")).to.be.true
  })

  it("works with mount functions and class name", function() {
    expect(mount(<MyFunction />).is(".foobar")).to.be.true
  })

})
```

### Mocha output
```
  Broken enzyme thing
    1) works with shallow classes and constructor
    2) works with shallow classes and display name
    ✓ works with shallow classes and class name
    3) works with shallow functions and constructor
    4) works with shallow functions and display name
    ✓ works with shallow functions and class name
    ✓ works with mount classes and constructor
    ✓ works with mount classes and display name
    5) works with mount classes and class name
    ✓ works with mount functions and constructor
    ✓ works with mount functions and display name
    6) works with mount functions and class name


  6 passing (304ms)
  6 failing

  1) Broken enzyme thing works with shallow classes and constructor:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:16:5)

  2) Broken enzyme thing works with shallow classes and display name:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:20:5)

  3) Broken enzyme thing works with shallow functions and constructor:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:28:5)

  4) Broken enzyme thing works with shallow functions and display name:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:32:5)

  5) Broken enzyme thing works with mount classes and class name:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:48:5)

  6) Broken enzyme thing works with mount functions and class name:
     AssertionError: expected false to be true
      at Context.<anonymous> (src/foo.test.js:60:5)
```

**Comment by Aweary** [comment]
@ahstro thanks for the report! The reason you're seeing this behavior is because shallow rendering does not render the component itself, it renders the output of the component one level deep. If you log out `wrapper.debug()` you can see whats actually rendered, which in this case would be:

```jsx
 <div className="foobar">Foo</div>
```

And not:

```jsx
<Foo>
  <div className="foobar">Foo</div>
</Foo>
```

The point is to assert on the render output. Assertions like `shallow(<MyFunction />).is(MyFunction)` don't tell you anything about your component, and are really just testing `shallow`, which we take care of 😉

`mount` works because it actually mounts and renders the full component.

**Comment by ahstro** [comment]
Oh, that cleared that up. Thank you!
