### ISSUE TITLE
Enzyme 2.5 breaking chai .attr assertions

### ISSUE THREAD

**Issue by harebenj** [airbnb/enzyme#633]
Upgraded Enzyme to 2.5 from 2.4.1 this morning and it started to break assertions like

    const myComponent = mount(<MyComponent />);

    expect(myComponent).to.have.attr('style', expectedStyle);

which is failing with:

     TypeError: Cannot read property 'call' of undefined
        at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1329:18)
        at ReactTestWrapper.get (node_modules/chai-enzyme/build/ReactTestWrapper.js:128:34)
        at ReactTestWrapper.attr (node_modules/chai-enzyme/build/ReactTestWrapper.js:49:15)
        at Assertion.<anonymous> (node_modules/chai-enzyme/build/assertions/generic.js:17:36)
        at Assertion.<anonymous> (node_modules/chai-enzyme/build/ChaiWrapper.js:136:19)
        at Assertion.ctx.(anonymous function) [as attr]    (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)

I couldn't find anything in the changelog about this causing a problem, was this supposed to be deprecated?

**Comment by ljharb** [comment]
This is fixed in v2.5.1.
