### ISSUE TITLE
setProps causes Invariant Violation

### ISSUE THREAD

**Issue by just-boris** [airbnb/enzyme#68]
given a simple test case

```es6
import {mount} from 'enzyme';

it('should update content', () => {
    function Foo({foo, id}) {
        const content = foo ? <span className="message">{id}</span> : id;
        return <div>{content}</div>;
    }
    const wrapper = mount(<Foo id="1" />);
    wrapper.setProps({ id: '1', foo: true});
    expect(wrapper.find('.message').length).toBe(1);
});
```

fails on the latest assertion with the error

```
Error: Invariant Violation: findComponentRoot(..., .7ng446bthc.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
    at invariant (../project/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.ReactMount.findComponentRoot (../project/node_modules/react/lib/ReactMount.js:764:54)
    at Object.ReactMount.findReactNodeByID (../project/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (../project/node_modules/react/lib/ReactMount.js:162:32)
    at ReactDOMComponent.Mixin.getPublicInstance (../project/node_modules/react/lib/ReactDOMComponent.js:925:29)
    at findAllInRenderedTreeInternal (../project/node_modules/enzyme/build/MountedTraversal.js:233:27)
    at findAllInRenderedTreeInternal (../project/node_modules/enzyme/build/MountedTraversal.js:246:26)
    at findAllInRenderedTreeInternal (../project/node_modules/enzyme/build/MountedTraversal.js:249:24)
    at treeFilter (../project/node_modules/enzyme/build/MountedTraversal.js:261:10)
    at ReactWrapper.<anonymous> (../project/node_modules/enzyme/build/ReactWrapper.js:37:45)
```

It happened when I conditionally render some elements. With shallow render it works fine.

**Comment by lelandrichardson** [comment]
are you using jsdom?  If so, perhaps try to ensure that the jsdom document get's loaded before you require enzyme or react... this might fix it.

I'm still trying to grapple with the different ways in which react depends on the `document`.  It seems we need to add more unit tests where we have components that conditionally render.

**Comment by just-boris** [comment]
Bug is still here in the gist: https://gist.github.com/just-boris/35da18d27eccdf4b6780

I tried to require React as late as it possible.

**Comment by lelandrichardson** [comment]
@just-boris i am going to spend some time over the holiday trying to figure this out. This is a thorny problem that doesn't have an obvious solution :/

**Comment by lelandrichardson** [comment]
Going to close this issue now. This invariant violation should not happen if you provide enzyme access to a global `document` before requiring react for the first time.

**Comment by just-boris** [comment]
Updated Enzyme to 2.0 version and used jsdom setup from [the documentation](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md).

Now it works fine. Thank you!

**Comment by Phuhwei** [comment]
Exactly, like I use AVA, require jsdom and enzyme in order:
`“require”: [
      “babel-register”,
      “ignore-styles”,
      “./test/config/setup-1-jsdom”,
      “./test/config/setup-2-enzyme”
    ]`
