### ISSUE TITLE
renderedChildren[key].getPublicInstance is not a function

### ISSUE THREAD

**Issue by roastedfrost** [airbnb/enzyme#689]
Hi,

I have an issue with enzyme

```javascript
class Test extends React.Component {
    render() {
        let a = "some";
        return (<div><div className="row">{ a }</div><div className="row">{ a }</div></div>); // it's ok               
    }
}
const wrapper = mount(<Test />);
wrapper.find('.row + .row'); 
```
Everything is works, I get this from wrapper.html():
```html
<div>
    <div class="row">some</div>
    <div class="row">some</div>
</div>
````

But for this one
```javascript
class Test extends React.Component {
    render() {
        let a = "some";
        let b = "text";
        return (<div><div className="row">{ a }{ b }</div><div className="row">{ a }{ b }</div></div>);
    }
}
const wrapper = mount(<Test />);
wrapper.find('.row + .row'); // fails
```
I've got
```html
<div>
    <div class="row">
        <!-- react-text: 3 -->some<!-- /react-text -->
        <!-- react-text: 4 -->text<!-- /react-text -->
    </div>
    <div class="row">
        <!-- react-text: 6 -->some<!-- /react-text -->
        <!-- react-text: 7 -->text<!-- /react-text -->
    </div>
</div>
```
and failure 
```
TypeError: renderedChildren[key].getPublicInstance is not a function
    at webpack:///~/enzyme/build/MountedTraversal.js:139:0 <- src/ui/tiledGrid.spec.js:40881:41
    at Array.map (native)
    at webpack:///~/enzyme/build/MountedTraversal.js:135:9 <- src/ui/tiledGrid.spec.js:40877:13
    at childrenOfInstInternal (webpack:///~/enzyme/build/MountedTraversal.js:142:5 <- src/ui/tiledGrid.spec.js:40884:7)
    at childrenOfInstInternal (webpack:///~/enzyme/build/MountedTraversal.js:121:0 <- src/ui/tiledGrid.spec.js:40863:13)
    at ComplexSelector.childrenOfInst (webpack:///~/enzyme/build/MountedTraversal.js:165:0 <- src/ui/tiledGrid.spec.js:40907:11)
    at webpack:///~/enzyme/build/ComplexSelector.js:168:0 <- src/ui/tiledGrid.spec.js:39408:35
    at Array.forEach (native)
    at traverseChildren (webpack:///~/enzyme/build/ComplexSelector.js:165:0 <- src/ui/tiledGrid.spec.js:39405:32)
    at webpack:///~/enzyme/build/ComplexSelector.js:180:0 <- src/ui/tiledGrid.spec.js:39420:14
```

React 15.3.2
Enzyme 2.5.1

**Comment by ljharb** [comment]
It seems we don't currently support the adjacent sibling selector - it should either work, or throw immediately with an error that says so.

**Comment by roastedfrost** [comment]
But ```wrapper.find('.row + .row'); ``` works fine for the first sample. Seems to be issue with ```react-text``` comment tag.

**Comment by ljharb** [comment]
Ah, good call, thanks (i read too quickly).
