### ISSUE TITLE
Unbalanced HTML attribute name selector results in "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by begincalendar** [airbnb/enzyme#794]
**Enzyme version: master**

# Code To Reproduce

```
const Foo = () => (                                                              
  <div>                                                                          
    <div data-name="xyz">Hello world!</div>                                      
  </div>                                                                         
);                                                                               
                                                                                 
const wrapper = mount(<Foo/>);                                                   
                                                                                 
const element = wrapper.find('div[data-name="xyz"'); // <------ Culprit
```

# Stacktrace

```
RangeError: Maximum call stack size exceeded                                     
                                                                                 
  at RegExp.[Symbol.replace] (native)                                            
  at RegExp.[Symbol.replace] (native)                                            
  at String.replace (native)                                                     
  at splitSelector (src/Utils.js:215:6)                                          
  at buildInstPredicate (src/MountedTraversal.js:277:20)
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)

  ...more repetitions of the frames below
                      
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at buildInstPredicate (src/MountedTraversal.js:277:44)                         
  at Array.map (native)                                                          
  at ComplexSelector.buildInstPredicate [as buildPredicate] (src/MountedTraversal.js:277:44)
  at recurseSelector (src/ComplexSelector.js:24:37)                              
  at ComplexSelector.handleSelectors (src/ComplexSelector.js:67:18)              
  at ComplexSelector.find (src/ComplexSelector.js:78:19)                         
  at ReactWrapper.find (src/ReactWrapper.jsx:411:33)
```

# Description

I don't know about Enzyme internals, but balancing the brackets does fix the problem, so it looks as if the unbalanced characteristic is at least part of the cause.

**Comment by ljharb** [comment]
Does the same thing happen with `shallow`?

**Comment by begincalendar** [comment]
Yep, `shallow` stacktrace is as follows:

```
RangeError: Maximum call stack size exceeded                                     
   at RegExp.[Symbol.replace] (native)                                           
   at RegExp.[Symbol.replace] (native)                                           
   at String.replace (native)                                                    
   at splitSelector (src/Utils.js:215:6)                                         
   at buildPredicate (src/ShallowTraversal.js:102:20)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
                                                                                 
   ...repeat below frames                                                        
                                                                                 
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at buildPredicate (src/ShallowTraversal.js:102:44)                            
   at Array.map (native)                                                         
   at ComplexSelector.buildPredicate (src/ShallowTraversal.js:102:44)            
   at recurseSelector (src/ComplexSelector.js:24:37)                             
   at ComplexSelector.handleSelectors (src/ComplexSelector.js:67:18)             
   at ComplexSelector.find (src/ComplexSelector.js:78:19)                        
   at ShallowWrapper.find (src/ShallowWrapper.js:455:33)
```

**Comment by begincalendar** [comment]
1. How is the API supposed to gracefully handle a malformed selector?
2. There appear to be a few libraries out there that parse CSS selectors. Could Enzyme depend on one of those to do the validation?

**Comment by ljharb** [comment]
I would hope that a malformed selector would throw immediately.

We've definitely planned for awhile now to replace our hacky css parsing with a selector library. See https://github.com/airbnb/enzyme/projects/1#card-1592301 for a few examples.

**Comment by avdhootpatil** [comment]
> Does the same thing happen with `shallow`?

It Doesn't happen with shallow
