### ISSUE TITLE
shallow() crashes when render returns null

### ISSUE THREAD

**Issue by sylvain-hamel** [airbnb/enzyme#820]
I have a component like this:

```
const Comp = ({condition})=> condition ? <div>someting</div> : null;
````

enzyme's `shallow` function crashes when I test with `shallow(<Comp condition={false}/>)` because of the `null` my component returns when `condition` is `false`.

**Comment by koba04** [comment]
@sylvain-hamel  I can't reproduce this. Can you share a small test case that reproduces this issue?

**Comment by sylvain-hamel** [comment]
@koba04 here it is:


```
import React from 'react';
import {shallow} from 'enzyme';

const Comp = ({condition})=> condition ? <div>Comp</div> : null;

fdescribe('Comp', () => {

  it('should render null ', ()=> {
    shallow(<Comp condition={false}/>);
  });

});
```

stack trace is 

stack trace is 

```
TypeError: inst.render is not a function
at ShallowComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (enzyme.2.7.1.js:46940:34)
at ShallowComponentWrapper.mountComponent (enzyme.2.7.1.js:46573:30)
at ShallowComponentWrapper.wrapper [as mountComponent] (enzyme.2.7.1.js:53415:21)
at ReactShallowRenderer._render (enzyme.2.7.1.js:54791:14)
at _batchedRender (enzyme.2.7.1.js:54773:12)
at Object.batchedUpdates (enzyme.2.7.1.js:49482:7)
at Object.batchedUpdates (enzyme.2.7.1.js:55261:20)
at ReactShallowRenderer.render (enzyme.2.7.1.js:54768:16)
at ReactShallowRenderer.render (enzyme.2.7.1.js:9816:39)
at enzyme.2.7.1.js:7678:26
at ReactDefaultBatchingStrategyTransaction.perform (enzyme.2.7.1.js:57197:20)
at Object.batchedUpdates (enzyme.2.7.1.js:49484:19)
at batchedUpdates (enzyme.2.7.1.js:55261:20)
at enzyme.2.7.1.js:7677:41
at withSetStateAllowed (enzyme.2.7.1.js:9394:3)
at new ShallowWrapper (enzyme.2.7.1.js:7676:38)
```

I am using a browserify build if that matters, see #806.

**Comment by koba04** [comment]
@sylvain-hamel Thanks! The cause seems to be a browserify build. Does it work without browserify build?

**Comment by ljharb** [comment]
What version of React are you using? SFCs can't return null until React 15.

**Comment by sylvain-hamel** [comment]
@ljharb I'm using 15.4.0

@koba04 I don't have an environment where I can test it without a browserify build. But if you say you can't reproduce the issue I guess neither would I. The tests case is rather simple. Any idea what could be wrong with the build?

**Comment by sylvain-hamel** [comment]
Issues resolved : My project does use react 15. But my tests ran under react 14. My browserify build of enzyme uses react 14 because by default the enzyme project is set to react 14 so when I browserifyed it, it embedded react 14 in the bundle.
