### ISSUE TITLE
`npm link` doesn't work.

### ISSUE THREAD

**Issue by trusktr** [airbnb/enzyme#862]
I was trying to test some changes using `npm link` to link enzyme into a local project, but linking doesn't work:

```
~/src/airbnb+enzyme > npm link
(node:31650) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN peerDependencies The peer dependency react included from enzyme will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> bufferutil@1.2.1 install /home/trusktr/src/airbnb+enzyme/node_modules/bufferutil
> node-gyp rebuild

(node:31663) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gyp: /home/trusktr/.node-gyp/6.3.1/common.gypi not found (cwd: /home/trusktr/src/airbnb+enzyme/node_modules/bufferutil) while reading includes of binding.gyp while tr
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/trusktr/imvu/website-project/node-binaries/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/home/trusktr/imvu/website-project/node-binaries/bin/node" "/home/trusktr/imvu/website-project/node-binaries/lib/node_modules/npm/node_modules/node-
gyp ERR! cwd /home/trusktr/src/airbnb+enzyme/node_modules/bufferutil
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/trusktr/imvu/website-project/node-binaries/bin/node" "/home/trusktr/imvu/website-project/node-binaries/bin/npm" "link"
npm ERR! node v6.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/trusktr/src/airbnb+enzyme/npm-debug.log
```

**Comment by ljharb** [comment]
Is `bufferutil` a dependency of your project, or a transitive dependency of enzyme (or something else)?

**Comment by aweary** [comment]
Looks like something related to your node install and `node-gyp`, you might try removing `~/.node-gyp` ([reference](https://github.com/nodejs/node-gyp/issues/819))
