### ISSUE TITLE
React-Native 0.43.1 Incompatible with Enzyme 2.8.0

### ISSUE THREAD

**Issue by Brian-Kaplan** [airbnb/enzyme#873]
The latest version of react-native 0.43.1 requires react 16.0.0-alpha.3 to work properly. Updating these two dependencies causes issues with Enzyme 2.8.0

Stack Trace

```
Error: Cannot find module 'react/lib/ReactComponentWithPureRenderMixin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/react-addons-pure-render-mixin/index.js:1:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/react-native-mock/build/react-native.js:113:17)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/react-native-mock/mock.js:1:25)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/mocha/bin/_mocha:345:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/brian.kaplan/repo/root/ae/appian-libraries/sail-client-native/SailClient/node_modules/mocha/bin/_mocha:344:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by nfcampos** [comment]
this sounds like an issue with react-native-mock, ie. it is importing `react-addons-pure-render-mixin` here, which AFAIK is not compatible with react 16
anyway, can we close this issue here? it seems to be tracked in the react-native-mock repo at https://github.com/RealOrangeOne/react-native-mock/issues/129, PR at https://github.com/RealOrangeOne/react-native-mock/issues/130

**Comment by Brian-Kaplan** [comment]
Ah I see, thanks
