### ISSUE TITLE
Shallow renderer produces "TypeError: Cannot read property 'props' of undefined" error

### ISSUE THREAD

**Issue by furkle** [airbnb/enzyme#903]
When I try to perform a basic shallow rendering test with the `shallow` function, I get the following error message:

 TypeError: Cannot read property 'props' of undefined
      
      at Object.ReactElement.cloneElement (node_modules/react/lib/ReactElement.js:271:34)
      at Object.ReactElementValidator.cloneElement (node_modules/react/lib/ReactElementValidator.js:242:48)
      at App.render (src/App.js:117:57)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext (node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
      at ReactCompositeComponent.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
      at ReactCompositeComponent.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactShallowRenderer._render (node_modules/react-dom/lib/ReactShallowRenderer.js:132:23)
      at _batchedRender (node_modules/react-dom/lib/ReactShallowRenderer.js:85:12)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:14)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at ReactShallowRenderer.render (node_modules/react-dom/lib/ReactShallowRenderer.js:112:18)
      at ReactShallowRenderer.render (node_modules/enzyme/build/react-compat.js:180:39)
      at node_modules/enzyme/build/ShallowWrapper.js:128:26
      at ReactDefaultBatchingStrategyTransaction.TransactionImpl.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at performBatchedUpdates (node_modules/enzyme/build/ShallowWrapper.js:106:42)
      at node_modules/enzyme/build/ShallowWrapper.js:127:9
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:284:3)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:126:38)
      at shallow (node_modules/enzyme/build/shallow.js:19:10)
      at Object.it (src/App.test.js:12:67)
      at process._tickCallback (internal/process/next_tick.js:103:7)

The render method of the `App` component is as follows:

```
render() {
	const id = this.props.selectedPane;

	let child = React.cloneElement(this.props.children, {
		appLogin: this.appLogin,
		appLogout: this.appLogout,
		createModal: this.createModal,
		closeModal: this.closeModal,
		togglePackagePublish: this.togglePackagePublish,
		editPackage: this.editPackage,
		removePackage: this.removePackage,
	});

	const backgroundStyle = (this.props.panes[id] || {}).style;

	return (
  		<div className="App">
        	    <div className="App-backgroundColor"></div>
        	    <div className="App-backgroundImage" style={backgroundStyle}></div>

        	    <Header
        		panes={this.props.panes}
        		selectedPane={this.props.selectedPane}
        		navBarItemClick={this.navBarItemClick} />

        	    {child}

		    <Footer />

        	    <div className={"Modal-container" + (this.props.modal ? "" : " hidden")}>
        		{this.props.modal}
        	    </div>
  		</div>
	);
}
```

Apologies if this is a common error -- I googled a bunch and checked the issue log, but couldn't find anything directly related.

**Comment by ljharb** [comment]
What does your shallow-render call look like? (specifically, what is the `children` prop)

**Comment by furkle** [comment]
It looks like so:

    it('renders App', () => {
        const app = shallow(<App />);
        expect(wrapper).to.have.length(1);
    });

Am I misunderstanding and do I need to be passing props in for the props object to exist in `App`?

**Comment by ljharb** [comment]
Absolutely you need to pass props into `App` if you want `this.props` to have anything inside it inside `App`. Where did you expect the `children` prop to come from?

**Comment by furkle** [comment]
That's not the problem I'm asking about -- `this` doesn't even exist within the `render` method, according to the error I posted. I fully expected `this.props` to be an empty object, but that's not what's happening.

**Comment by ljharb** [comment]
The error is coming from inside `cloneElement`, because `this.props.children` (not `this.props` or `this`) is undefined - see the top lines of the stack trace.

**Comment by furkle** [comment]
My apologies, I misunderstood the stack trace to be pointing to the props in `this.props.children` and thought that the render function was becoming unbound. Sorry if I wasted your time -- please feel free to close/delete the issue. Thanks for your help.
