### ISSUE TITLE
Accessing element properties after unmounting and remounting throws Invariant Violation

### ISSUE THREAD

**Issue by AkshatM** [airbnb/enzyme#967]
Enzyme Version 2.7.1. Windows 7 with Node 6.10.3.

Code that demonstrates the issue:

```jsx
class WrappedComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      currentText: DEFAULT_TEXT,
    };
  }

  render() {
    return (<div className="test">{this.state.currentText}</div>);
  }
}

/* In my actual tests folder using Jest */

const renderedComponent = mount(<WrappedComponent />);
expect(renderedComponent.text()).toBe(DEFAULT_TEXT);  // passes

renderedComponent.unmount();
renderedComponent.mount();
expect(renderedComponent.text()).toBe(DEFAULT_TEXT);  // throws exception
```

This raises the following exception: 
```
Invariant Violation: findDOMNode was called on an unmounted component.
  at invariant (node_modules\fbjs\lib\invariant.js:44:15)
  at findDOMNode (node_modules\react-dom\lib\findDOMNode.js:53:54)
  at ReactWrapper.<anonymous> (node_modules\enzyme\build\ReactWrapper.js:707:47)
  at ReactWrapper.single (node_modules\enzyme\build\ReactWrapper.js:1421:25)
  at ReactWrapper.text (node_modules\enzyme\build\ReactWrapper.js:706:21)
```

# Some Investigation

It looks like (surprise, surprise) `mount()` after `unmount()` does not actually yield anything:

```jsx
console.log(renderedComponent.debug());
// correctly renders expected structure, is consistent with .html()
// <WrappedComponent currentText="">
//    <div className="test">
//        Default text to display when no data is available.
//    </div>
// </WrappedComponent>

renderedComponent.unmount();
console.log(renderedComponent.debug());  // blank, accessing .html() throws error above

renderedComponent.mount();
console.log(renderedComponent.debug());  // blank, accessing .html() throws error above
```

I would surmise from [the documentation](http://airbnb.io/enzyme/docs/api/ReactWrapper/unmount.html) that this is not the expected behaviour.

**Comment by ljharb** [comment]
This seems heavily related to #956.

However, I wouldn't expect a test to ever need to re-mount an unmounted component wrapper - although I'd expect it to work (i'd expect "testing unmounting" and "testing mounting" to always be done in separate "it" blocks).

**Comment by AkshatM** [comment]
@ljharb In my case, we're testing an HOC that makes a call on mount to local storage to retrieve cached data, and saves data from the wrapped component on unmounting. 

The only strategy I have so far is to simulate a full remounting, including unmounting and mounting. [Jest's code execution order](https://gist.github.com/tamlyn/dd6d54cdbe6eccd51a4bc61f5844bec4) makes it impossible for me to test this in independent "it" blocks, since `unmount` and `mount` would be invoked before any of my tests begin.

Do you have suggestions on how to tackle this issue otherwise?

**Comment by ljharb** [comment]
I think a single "it" using `mount` would test the retrieval, and then in the same "it", `.unmount` would let you test the saving. I don't know why you'd need to test "remounting", since mount + unmount already covers that (you do not need to, and should not be, testing React itself)

**Comment by AkshatM** [comment]
Fair enough. I can do that.

I still believe this should be considered a bug, though. That, or the documentation should be updated accordingly so that people don't fall into the same trap I did, as the example there clearly indicates it is possible to unmount and remount in this manner.

**Comment by ljharb** [comment]
I absolutely agree that it's a bug, even if it's weird :-) which i think is a duplicate of #956 (open PR: #969); but let's keep this open as well just in case.
