### ISSUE TITLE
find by prop does not work, use mount

### ISSUE THREAD

**Issue by SVITY** [airbnb/enzyme#987]
Hello, guys. Please, help me. Why the second and the third test cases don't work?

Code:
```jsx
import React from 'react';
import { mount } from 'enzyme';

class InputWrapper extends React.Component {
  render() {
    return <div>
      <label>Label for input</label>
      <input type="text" />
    </div>
  }
}

class Details extends React.Component {
  render() {
    return (
      <div>
        <InputWrapper testId="testInput" />
      </div>
    );
  }
}

describe('test suite', () => {
  const wrapper = mount(<Details />);

  console.log(wrapper.debug());

  it('test case', () => {
    const test = wrapper.findWhere((node) => {
      return node.prop('testId') === 'testInput';
    });

    expect(test.length).toBe(1);
  });

  it('test case 2', () => {
    const test = wrapper.find({ testId: 'testInput' });

    expect(test.length).toBe(1);
  });

  it('test case 3', () => {
    const test = wrapper.find('[testId="testInput"]');

    expect(test.length).toBe(1);
  });
});

```

Result:
```sh
  ● test suite › test case 2

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at Object.<anonymous> (src/components/CreateListing/Details/__tests__/tempTest.js:39:25)
      at process._tickCallback (node.js:368:9)

  ● test suite › test case 3

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at Object.<anonymous> (src/components/CreateListing/Details/__tests__/tempTest.js:45:25)
      at process._tickCallback (node.js:368:9)

  test suite
    ✓ test case (2ms)
    ✕ test case 2 (1ms)
    ✕ test case 3 (1ms)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        1.256s, estimated 2s
Ran all test suites matching /temp/.

  console.error node_modules/react/node_modules/fbjs/lib/warning.js:36
    Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types

  console.log src/components/CreateListing/Details/__tests__/tempTest.js:26
```
```jsx
    <Details>
      <div>
        <InputWrapper testId="testInput">
          <div>
            <label>
              Label for input
            </label>
            <input type="text" />
          </div>
        </InputWrapper>
      </div>
    </Details>

```

**Comment by ljharb** [comment]
I believe `.find` searches the DOM nodes, none of which have `testId`.

**Comment by SVITY** [comment]
@ljharb Using `.findWhere` function is the only one way to find non-DOM node,  isn't it?

**Comment by ljharb** [comment]
Off the top of my head I'm not certain, but that sounds right to me. Regardless, it's the best API of the three because you can use a function to specify what you want.
