### ISSUE TITLE
touchTap event with Full Dom Renderer.

### ISSUE THREAD

**Issue by hourliert** [airbnb/enzyme#99]
Hi,

I am trying to test a component which use material-ui components. These component depends on https://github.com/zilverline/react-tap-event-plugin.

When I use the shallow renderer and if I `injectTapEventPlugin` at the beginning of my test file. I could simulate the `touchTap` event.

For instance: 

```javascript
 const callback = sinon.spy();
 const wrapper = shallow(
   <LinksList
     onLinkTouch={callback}
     links={menuItems}
   />, {
     context: { accessLevel },
   }
 );

 expect(callback).to.not.have.been.called();
 wrapper.find(MenuItem).first().simulate('touchTap');
 expect(callback).to.have.been.called();
```

works great.

But when I use the Full dom renderer, `TestUtils.Simulate` doesn't seems to have access to the `touchTap` event.

This doesn't work:
```javascript
const callback = sinon.spy();
const wrapper = mount((
  contextStub(
    <LoginForm
      onSubmit={callback}
    />,
    context
  )
));

expect(callback).to.not.have.been.called();
wrapper.find(RaisedButton).last().find(EnhancedButton).simulate('touchTap');
expect(callback).to.have.been.called();
```

And I get this error: 
```
     TypeError: Cannot read property 'apply' of undefined
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:351:44)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:739:17)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:350:12)
      at Context.<anonymous> (LoginForm-test.js:67:30)
```

Do you know how I can solve this issue?
Thanks.

**Comment by blainekasten** [comment]
I'm guessing you are using React 0.13? Enzyme's Simulate is essentially a wrapper around React's TestUtils.Simulate. React's simulate methods are based on what get's injected into their internal stuff. I think in 0.13 if you didn't call `React.initializeTouchEvents(true);` manually, the events weren't added internally. 

If you aren't using 0.13, then I can look more into what would be causing this in 0.14. But I think this is a 0.13 issue where you just need to call that method. (probably at the top of your test)

**Comment by blainekasten** [comment]
#79

**Comment by hourliert** [comment]
Hi,

I am using React 0.14.

Here is my package.json

```
{
  "name": "react-boilerplate",
  "version": "0.0.0",
  "description": "Yet Another React Boilerplate.",
  "engines": {
    "node": ">=4.1 <5",
    "npm": ">=3.3 <4"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hourliert/react-seed.git"
  },
  "keywords": [
    "react",
    "seed"
  ],
  "author": "Thomas Hourlier <hourliert@gmail.com> (https://github.com/hourliert)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/hourliert/react-seed/issues"
  },
  "homepage": "https://github.com/hourliert/react-seed#readme",
  "scripts": {
    "lint": "gulp lint",
    "test": "gulp coverage",
    "build": "gulp bundle",
    "start": "gulp serve"
  },
  "dependencies": {
    "flux-standard-action": "^0.6.0",
    "history": "~1.13.0",
    "immutable": "^3.7.6",
    "invariant": "^2.2.0",
    "isomorphic-fetch": "^2.2.0",
    "material-ui": "^0.14.0-rc2",
    "radium": "^0.15.3",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-redux": "^4.0.0",
    "react-router": "^1.0.2",
    "react-tap-event-plugin": "^0.2.1",
    "redux": "^3.0.4",
    "redux-actions": "^0.9.0",
    "redux-form": "^4.0.5",
    "redux-immutablejs": "0.0.8",
    "redux-logger": "^2.3.1",
    "redux-promise-middleware": "^2.3.2",
    "redux-simple-router": "^1.0.2",
    "redux-thunk": "^1.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.3.17",
    "babel-eslint": "^5.0.0-beta6",
    "babel-loader": "^6.2.0",
    "babel-plugin-add-module-exports": "^0.1.1",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-transform-decorators-legacy": "^1.3.3",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "browser-sync": "^2.9.11",
    "chai": "^3.4.1",
    "del": "^2.0.2",
    "dirty-chai": "^1.2.2",
    "enzyme": "^1.2.0",
    "eslint-config-airbnb": "^2.1.1",
    "eslint-config-react": "^1.1.1",
    "eslint-plugin-react": "^3.11.3",
    "express": "^4.13.3",
    "fetch-mock": "^4.0.0",
    "file-loader": "^0.8.4",
    "gulp": "^3.9.0",
    "gulp-eslint": "^1.1.1",
    "gulp-istanbul": "^0.10.3",
    "gulp-jscs": "^3.0.2",
    "gulp-mocha": "^2.2.0",
    "gulp-replace": "^0.5.4",
    "gulp-util": "^3.0.7",
    "isparta": "^4.0.0",
    "jsdom": "^7.2.1",
    "json-loader": "^0.5.3",
    "mocha": "^2.3.4",
    "mockery": "^1.4.0",
    "multi-progress": "^1.0.0",
    "raw-loader": "^0.5.1",
    "react-addons-test-utils": "^0.14.0",
    "react-transform-hmr": "^1.0.1",
    "redux-devtools": "^3.0.0",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",
    "run-sequence": "^1.1.4",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.8.0",
    "source-map-support": "^0.4.0",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.9",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.2.0"
  }
}
```

**Comment by blainekasten** [comment]
Okay, it took me a minute to track along with everything that is happening. The shallowWrapper's simulate method is directly derived from the `TestUtils.createRenderer().render().simulate`. So it's no surprise that one works. 

Obviously your use case is very abnormal, and I don't think React Core would suggest the use of that plugin as it's hacking into the internals of React. They have yet to expose the Event Plugin API, so you _might_ not like the results you get.

The mounted wrapper is basically a wrapper around the `TestUtils.Simulate[event]` method. Would you be able to test your use case with vanilla react TestUtils.Simulate and see if it works? If it doesn't work there, then enzyme probably can't do anything for this situation.

**Comment by hourliert** [comment]
Hi,

I tried this:

```javascript
expect(callback).to.not.have.been.called();
const button = TestUtils.findRenderedDOMComponentWithTag(wrapper.instance(), 'button');
const node = ReactDOM.findDOMNode(button);
TestUtils.Simulate.touchTap(node);
expect(callback).to.have.been.called();
```

And it worked great.
In this case, the `touchTap` method is attached to the object `TestUtils.Simulate`, as expected.

**Comment by lelandrichardson** [comment]
Has this issue been fixed? Was it actually a bug?

**Comment by zuk** [comment]
I still can't use enzyme's `simulate('touchTap')` with `mount()` in React 0.14.7.

**Comment by Aweary** [comment]
@zuk `simulate` wraps `ReactTestUtils.Simulate` in `mount()` and React doesn't recognize/support `touchTap` as an event: https://facebook.github.io/react/docs/events.html#supported-events

I believe `ReactTestUtils`/`React` would have to be updated to support `touchTap` for this to work as expected, otherwise an exception for `touchTap` would have to to be hard coded into `simulate` which seems less than ideal.

**Comment by joncursi** [comment]
I can confirm that attempting a `touchTap` event simulation on a mounted element does not work, whereas going with React's internal testing utilities will work if https://github.com/zilverline/react-tap-event-plugin is initialized.

Does not work:

```jsx
      const wrapper = mount(<AppLayout />);
      expect(
        wrapper.state().drawerOpen
      ).toEqual(false);
      wrapper.find('button').simulate('touchTap'); // fails here
      expect(
        wrapper.state().drawerOpen
      ).toEqual(true);
```

Works (provided that `injectTapEventPlugin()` has been called:

```jsx
      const wrapper = mount(<AppLayout />);
      expect(
        wrapper.state().drawerOpen
      ).toEqual(false);

      const node = ReactDOM.findDOMNode(
        ReactTestUtils.findRenderedDOMComponentWithTag(
          wrapper.instance(), 'button'
        )
      );
      ReactTestUtils.Simulate.touchTap(node);

      expect(
        wrapper.state().drawerOpen
      ).toEqual(true);
```

**Comment by zuk** [comment]
We ended up writing a helper function that tries to use the right touchTap simulation strategy automatically:

```
export function simulateEvent(wrappedTarget, eventType) {
  if (wrappedTarget.node) {
    // wrappedTarget was obtained using enzyme's mount()
    const button = wrappedTarget.node
    const node = ReactDOM.findDOMNode(button)
    TestUtils.Simulate[eventType](node)
  } else {
    // wrappedTarget was obtained using enzyme's shallow()
    wrappedTarget.simulate('touchTap')
  }
}
```

**Comment by joncursi** [comment]
@zuk very clean solution, works great! Thank you!

**Comment by lelandrichardson** [comment]
@zuk keep in mind that enzyme exports some things that can make this even cleaner...

```
import { ShallowWrapper, ReactWrapper } from 'enzyme';

ShallowWrapper.prototype.simulate = ((original) => function simulate(...args) {
  // your own version of simulate... potentially calling the original one in some cases
})(ShallowWrapper.prototype.simulate);
```

**Comment by swenyang** [comment]
I found the code below works on both `shallow` and `mount`, no need to import `react-addons-test-utils` (I'm using enzyme 3.3.0, jest 22.1.3):

```js
import Enzyme, { shallow } from 'enzyme'
import Adapter from 'enzyme-adapter-react-15.4'
import injectTapEventPlugin from 'react-tap-event-plugin'

injectTapEventPlugin()
Enzyme.configure({ adapter: new Adapter() })

describe('Button', () => {
    test('test click', () => {
        const callback = jest.fn()
        const wrapper = shallow(
            <Button onTouchTap={callback}>Sample</Button>
        )
        wrapper.find('button').first().simulate('touchTap')
        expect(callback.mock.calls.length).toBe(1)
    })
})
```
